export class Constants {
    static readonly MOD_NAMESPACE = "tinyIcons";

    static readonly TRANSLATION_KEYS = {
        // TODO: May be retrievable through game base translations
        MODIFIER_SCOPES: {
            SKILL: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_SKILL`,
            DAMAGE_TYPE: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_DAMAGE_TYPE`,
            REALM: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_REALM`,
            CURRENCY: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_CURRENCY`,
            CATEGORY: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_CATEGORY`,
            ACTION: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_ACTION`,
            SUBCATEGORY: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_SUBCATEGORY`,
            ITEM: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_ITEM`,
            EFFECT_GROUP: `${this.MOD_NAMESPACE}_MODIFIER_SCOPES_EFFECT_GROUP`,
        },

        SETTINGS: {
            RELOAD_REQUIRED: `${this.MOD_NAMESPACE}_SETTINGS_RELOAD_TEXT`,
            SAVE_AND_RELOAD: `${this.MOD_NAMESPACE}_SETTINGS_SAVE_AND_RELOAD_TEXT`,
            GLOBAL_ICONS: {
                LABEL: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_GLOBAL_ICONS_LABEL`,
                HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_GLOBAL_ICONS_HINT`
            },
            SECONDARY_ICONS: {
                LABEL: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SECONDARY_ICONS_LABEL`,
                HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SECONDARY_ICONS_HINT`
            },
            PLACEHOLDER_ICONS: {
                LABEL: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_PLACEHOLDER_ICONS_LABEL`,
                HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_PLACEHOLDER_ICONS_HINT`
            },
            SCOPE_ICONS: {
                LABEL: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_LABEL`,
                HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_HINT`,
                OPTIONS: {
                    SKILL_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_SKILL_HINT`,
                    DAMAGE_TYPE_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_DAMAGE_TYPE_HINT`,
                    REALM_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_REALM_HINT`,
                    CURRENCY_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_CURRENCY_HINT`,
                    CATEGORY_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_CATEGORY_HINT`,
                    ACTION_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_ACTION_HINT`,
                    SUBCATEGORY_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_SUBCATEGORY_HINT`,
                    ITEM_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_ITEM_HINT`,
                    EFFECT_GROUP_HINT: `${this.MOD_NAMESPACE}_SETTINGS_SETTING_SCOPE_ICONS_OPTION_EFFECT_GROUP_HINT`,
                }
            }
        }
    }
}