import { AllIconTags } from './ModifierIcons';

/**
 * An object mapping all modifiers to tags that represent relevant icons.
 */
export const modifierTags: {
  [key: string]: AllIconTags[];
} = {
  increasedGlobalAccuracy: ['ti_combat_up'],
  increasedMeleeAccuracyBonus: ['offense_up', 'combat'],
  increasedMeleeMaxHit: ['ti_strength_up', 'combat'],
  increasedMeleeEvasion: ['evasion_up', 'combat'],
  increasedRangedAccuracyBonus: ['ti_ranged_up', 'combat'],
  increasedRangedMaxHit: ['ti_ranged_up', 'combat'],
  increasedRangedEvasion: ['ti_ranged_up', 'combat'],
  increasedMagicAccuracyBonus: ['ti_magic_up', 'combat'],
  increasedMagicMaxHit: ['ti_magic_up', 'combat'],
  increasedMagicEvasion: ['ti_magic_up', 'combat'],
  increasedMaxHitFlat: ['ti_combat_up'],
  increasedMaxHitPercent: ['ti_combat_up'],
  increasedDamageReduction: ['ti_dr_up', 'combat'],
  increasedChanceToDoubleLootCombat: ['combat', 'loot'],
  increasedSlayerCoins: ['slayer_coins', 'shop'],
  increasedHPRegenFlat: ['hitpoints', 'combat'],
  increasedGPGlobal: ['gp'],
  increasedGPFromMonsters: ['gp', 'combat'],
  increasedGPFromMonstersFlat: ['gp', 'combat'],
  increasedGPFromThieving: ['thieving', 'gp'],
  increasedGPFromThievingFlat: ['thieving', 'gp'],
  increasedGPFromAgility: ['agility', 'gp'],
  decreasedGPFromAgility: ['agility', 'gp'],
  increasedDamageToBosses: ['dungeon', 'combat'],
  increasedDamageToSlayerTasks: ['slayer', 'combat'],
  increasedDamageToSlayerAreaMonsters: ['slayer', 'combat'],
  increasedDamageToCombatAreaMonsters: ['combat'],
  increasedDamageToDungeonMonsters: ['dungeon', 'combat'],
  increasedDamageToAllMonsters: ['combat'],
  increasedAutoEatEfficiency: ['autoeat', 'hitpoints'],
  increasedAutoEatThreshold: ['autoeat', 'hitpoints'],
  increasedAutoEatHPLimit: ['autoeat', 'hitpoints'],
  increasedFoodHealingValue: ['hitpoints', 'combat'],
  increasedChanceToPreservePrayerPoints: ['prayer', 'combat'],
  increasedFlatPrayerCostReduction: ['prayer', 'combat'],
  increasedMinAirSpellDmg: ['ti_magic_up', 'combat'],
  increasedMinWaterSpellDmg: ['ti_magic_up', 'combat'],
  increasedMinEarthSpellDmg: ['ti_magic_up', 'combat'],
  increasedMinFireSpellDmg: ['ti_magic_up', 'combat'],
  increasedAmmoPreservation: ['ranged', 'preservation'],
  increasedRunePreservation: ['magic', 'preservation'],
  increasedHiddenSkillLevel: ['skill', 'combat'],
  decreasedAttackInterval: ['ti_attack_interval', 'ti_combat_up'],
  decreasedAttackIntervalPercent: ['ti_attack_interval', 'ti_combat_up'],
  increasedSlayerAreaEffectNegationFlat: ['slayer', 'combat'],
  decreasedMonsterRespawnTimer: ['combat'],
  decreasedGlobalAccuracy: ['ti_combat_dn'],
  decreasedMeleeAccuracyBonus: ['offense_dn', 'combat'],
  decreasedMeleeMaxHit: ['ti_strength_dn', 'combat'],
  decreasedMeleeEvasion: ['evasion_dn', 'combat'],
  decreasedRangedAccuracyBonus: ['ti_ranged_dn', 'combat'],
  decreasedRangedMaxHit: ['ti_ranged_dn', 'combat'],
  decreasedRangedEvasion: ['ti_ranged_dn', 'combat'],
  decreasedMagicAccuracyBonus: ['ti_magic_dn', 'combat'],
  decreasedMagicMaxHit: ['ti_magic_dn', 'combat'],
  decreasedMagicEvasion: ['ti_magic_dn', 'combat'],
  decreasedMaxHitFlat: ['ti_combat_dn'],
  decreasedMaxHitPercent: ['ti_combat_dn'],
  decreasedDamageReduction: ['ti_dr_dn', 'combat'],
  decreasedChanceToDoubleLootCombat: ['combat', 'loot'],
  decreasedSlayerCoins: ['slayer_coins', 'shop'],
  decreasedHPRegenFlat: ['hitpoints', 'combat'],
  decreasedGPGlobal: ['gp'],
  decreasedGPFromMonsters: ['gp', 'combat'],
  decreasedGPFromMonstersFlat: ['gp', 'combat'],
  decreasedDamageToBosses: ['dungeon', 'combat'],
  decreasedDamageToSlayerTasks: ['slayer', 'combat'],
  decreasedDamageToSlayerAreaMonsters: ['slayer', 'combat'],
  decreasedDamageToCombatAreaMonsters: ['combat'],
  decreasedDamageToDungeonMonsters: ['dungeon', 'combat'],
  decreasedDamageToAllMonsters: ['combat'],
  decreasedAutoEatEfficiency: ['autoeat', 'hitpoints'],
  decreasedAutoEatThreshold: ['autoeat', 'hitpoints'],
  decreasedAutoEatHPLimit: ['autoeat', 'hitpoints'],
  decreasedFoodHealingValue: ['hitpoints', 'combat'],
  decreasedChanceToPreservePrayerPoints: ['prayer', 'preservation'],
  decreasedFlatPrayerCostReduction: ['prayer', 'combat'],
  decreasedMinAirSpellDmg: ['ti_magic_dn', 'combat'],
  decreasedMinWaterSpellDmg: ['ti_magic_dn', 'combat'],
  decreasedMinEarthSpellDmg: ['ti_magic_dn', 'combat'],
  decreasedMinFireSpellDmg: ['ti_magic_dn', 'combat'],
  decreasedAmmoPreservation: ['ranged', 'preservation'],
  decreasedRunePreservation: ['magic', 'preservation'],
  decreasedHiddenSkillLevel: ['skill', 'combat'],
  increasedAttackInterval: ['ti_attack_interval', 'ti_combat_dn'],
  increasedAttackIntervalPercent: ['ti_attack_interval', 'ti_combat_dn'],
  increasedMonsterRespawnTimer: ['combat'],
  decreasedSlayerAreaEffectNegationFlat: ['slayer', 'combat'],
  increasedGPFromSales: ['gp', 'bank'],
  increasedBankSpace: ['bank'],
  increasedBankSpaceShop: ['bank'],
  increasedChanceToPreservePotionCharge: ['potion', 'preservation'],
  decreasedGPFromSales: ['gp'],
  decreasedBankSpace: ['bank'],
  decreasedBankSpaceShop: ['bank'],
  decreasedChanceToPreservePotionCharge: ['potion', 'preservation'],
  decreasedSkillInterval: ['skill', 'interval'],
  decreasedSkillIntervalPercent: ['skill', 'interval'],
  increasedGlobalMasteryXP: ['mastery'],
  increasedGlobalSkillXP: ['skill'],
  decreasedGlobalSkillXP: ['skill'],
  increasedMasteryXP: ['skill', 'mastery'],
  increasedSkillXP: ['skill', 'skill'],
  increasedMiningNodeHP: ['mining'],
  increasedSkillInterval: ['skill', 'interval'],
  increasedSkillIntervalPercent: ['skill', 'interval'],
  decreasedGlobalMasteryXP: ['mastery'],
  decreasedMasteryXP: ['skill', 'mastery'],
  decreasedSkillXP: ['skill', 'skill'],
  decreasedMiningNodeHP: ['mining'],
  decreasedGPFromThieving: ['thieving', 'gp'],
  decreasedGPFromThievingFlat: ['thieving', 'gp'],
  dungeonEquipmentSwapping: ['equip_swap', 'dungeon'],
  increasedEquipmentSets: ['equip_set', 'combat'],
  autoSlayerUnlocked: ['auto_slayer', 'combat'],
  increasedTreeCutLimit: ['woodcutting'],
  increasedGlobalPreservationChance: ['preservation'],
  decreasedGlobalPreservationChance: ['preservation'],
  increasedFarmingYield: ['farming', 'loot'],
  decreasedFarmingYield: ['farming', 'loot'],
  increasedMaxHitpoints: ['hitpoints', 'combat'],
  decreasedMaxHitpoints: ['hitpoints', 'combat'],
  increasedFlatMaxHitpoints: ['hitpoints', 'combat'],
  decreasedFlatMaxHitpoints: ['hitpoints', 'combat'],
  increasedSlayerTaskLength: ['slayer', 'combat'],
  decreasedSlayerTaskLength: ['slayer', 'combat'],
  increasedChanceToDoubleItemsSkill: ['skill', 'double'],
  decreasedChanceToDoubleItemsSkill: ['skill', 'double'],
  increasedChanceToDoubleItemsGlobal: ['double'],
  decreasedChanceToDoubleItemsGlobal: ['double'],
  increasedLifesteal: ['hitpoints', 'combat'],
  decreasedLifesteal: ['hitpoints', 'combat'],
  increasedReflectDamage: ['ti_combat_up'],
  decreasedReflectDamage: ['ti_combat_dn'],
  increasedSkillPreservationChance: ['skill', 'preservation'],
  decreasedSkillPreservationChance: ['skill', 'preservation'],
  increasedChanceToDoubleOres: ['mining', 'double'],
  decreasedChanceToDoubleOres: ['mining', 'double'],
  increasedHitpointRegeneration: ['hitpoints', 'combat'],
  decreasedHitpointRegeneration: ['hitpoints', 'combat'],
  golbinRaidWaveSkipCostReduction: ['golbin', 'combat'],
  golbinRaidIncreasedMaximumAmmo: ['golbin', 'combat'],
  golbinRaidIncreasedMaximumRunes: ['golbin', 'combat'],
  golbinRaidIncreasedMinimumFood: ['golbin', 'combat'],
  golbinRaidIncreasedPrayerLevel: ['golbin', 'combat'],
  golbinRaidIncreasedPrayerPointsStart: ['golbin', 'combat'],
  golbinRaidIncreasedPrayerPointsWave: ['golbin', 'combat'],
  golbinRaidIncreasedStartingRuneCount: ['golbin', 'combat'],
  golbinRaidPassiveSlotUnlocked: ['golbin', 'combat'],
  golbinRaidPrayerUnlocked: ['golbin', 'combat'],
  golbinRaidStartingWeapon: ['golbin', 'combat'],
  increasedMinHitBasedOnMaxHit: ['ti_combat_up'],
  decreasedMinHitBasedOnMaxHit: ['ti_combat_dn'],
  increasedPotionChargesFlat: ['potion'],
  decreasedPotionChargesFlat: ['potion'],
  increasedBirdNestDropRate: ['woodcutting', 'bird_nest'],
  decreasedBirdNestDropRate: ['woodcutting', 'bird_nest'],
  increasedChanceNoDamageMining: ['mining'],
  decreasedChanceNoDamageMining: ['mining'],
  increasedSeeingGoldChance: ['mining'],
  decreasedSeeingGoldChance: ['mining'],
  increasedChanceDoubleHarvest: ['farming', 'double'],
  decreasedChanceDoubleHarvest: ['farming', 'double'],
  increasedChanceForElementalRune: ['runecrafting'],
  decreasedChanceForElementalRune: ['runecrafting'],
  increasedElementalRuneGain: ['runecrafting'],
  decreasedElementalRuneGain: ['runecrafting'],
  increasedChanceRandomPotionHerblore: ['herblore', 'potion'],
  decreasedChanceRandomPotionHerblore: ['herblore', 'potion'],
  increasedAttackRolls: ['ti_combat_up'],
  decreasedAttackRolls: ['ti_combat_dn'],
  freeBonfires: ['firemaking'],
  increasedAltMagicSkillXP: ['magic', 'skill'],
  decreasedAltMagicSkillXP: ['magic', 'skill'],
  increasedChanceToConvertSeedDrops: ['combat', 'seed'],
  aprilFoolsIncreasedMovementSpeed: ['lemon'],
  aprilFoolsDecreasedMovementSpeed: ['lemon'],
  aprilFoolsIncreasedTeleportCost: ['lemon'],
  aprilFoolsDecreasedTeleportCost: ['lemon'],
  aprilFoolsIncreasedUpdateDelay: ['lemon'],
  aprilFoolsDecreasedUpdateDelay: ['lemon'],
  aprilFoolsIncreasedLemonGang: ['lemon'],
  aprilFoolsDecreasedLemonGang: ['lemon'],
  aprilFoolsIncreasedCarrotGang: ['lemon'],
  aprilFoolsDecreasedCarrotGang: ['lemon'],
  increasedGPOnEnemyHit: ['gp', 'combat'],
  decreasedGPOnEnemyHit: ['gp', 'combat'],
  increasedAdditionalRunecraftCountRunes: ['runecrafting'],
  decreasedAdditionalRunecraftCountRunes: ['runecrafting'],
  increasedGPFromMonstersFlatBasedOnEvasion: ['gp', 'combat'],
  increasedGPPerMeleeDamage: ['gp', 'combat'],
  increasedGPPerRangedDamage: ['gp', 'ranged'],
  increasedGPPerMagicDamage: ['gp', 'magic'],
  increasedGPFromSlayerTaskMonsters: ['gp', 'slayer'],
  increasedGPWhenHitBasedOnDR: ['gp', 'defence'],
  increasedGPOnRegenBasedOnHPGain: ['gp', 'hitpoints'],
  increasedGPFromBurningMonsters: ['gp', 'combat'],
  summoningSynergy_1_2: ['summoning', 'combat'],
  increasedFlatMagicDefenceBonus: ['ti_magic_up', 'defence'],
  decreasedSlayerTaskMonsterAccuracy: ['slayer', 'ti_combat_up'],
  increasedMeleeRangedDefenceBonusBasedOnDR: ['ti_dr_up'],
  increasedHPRegenWhenEnemyHasMoreEvasion: ['hitpoints', 'combat'],
  summoningSynergy_1_15: ['summoning', 'combat'],
  increasedSCfromLifesteal: ['slayer_coins', 'hitpoints'],
  increasedHealingOnAttackBasedOnDR: ['ti_combat_up', 'hitpoints'],
  increasedSummoningAttackLifesteal: ['summoning', 'combat'],
  increasedWoodcuttingGemChance: ['woodcutting'],
  increasedBonusFishingSpecialChance: ['fishing'],
  summoningSynergy_3_9: ['summoning', 'cooking'],
  increasedRunecraftingStavePreservation: ['runecrafting'],
  summoningSynergy_Ent_Leprechaun: ['thieving', 'bird_nest'],
  increasedWoodcuttingJewelryChance: ['woodcutting'],
  summoningSynergy_3_17: ['woodcutting', 'smithing'],
  increasedMinimumBirdNestsWhenPotionActive: ['woodcutting', 'bird_nest'],
  summoningSynergy_3_19: ['woodcutting', 'firemaking'],
  summoningSynergy_4_5: ['mining', 'fishing'],
  decreasedCookingSuccessCap: ['cooking'],
  doubleRuneEssenceMining: ['mining'],
  summoningSynergy_Mole_Leprechaun: ['mining'],
  doubleSilverGoldMining: ['mining'],
  increasedMiningBarChance: ['mining'],
  increasedMiningNodeHPWithPerfectSwing: ['mining'],
  summoningSynergy_4_19: ['firemaking'],
  increasedFishingCookedChance: ['fishing', 'cooking'],
  increasedRunecraftingWaterComboRunes: ['runecrafting'],
  summoningSynergy_Octopus_Leprechaun: ['thieving'],
  increasedCraftingJewelryRandomGemChance: ['crafting'],
  increasedSmithingDragonGearPreservation: ['smithing'],
  increasedFishermansPotionCharges: ['fishing', 'potion'],
  summoningSynergy_6_7: ['ti_combat_up', 'summoning'],
  increasedMagicMinHitBasedOnMaxHitSlayerTask: ['ti_magic_up', 'slayer'],
  increasedMeleeMaxHitBasedOnMaxHitSlayerTask: ['ti_strength_up', 'slayer'],
  summoningSynergy_6_13: ['ti_dr_up', 'summoning'],
  increasedFlatHPRegenBasedOnMeleeMaxHit: ['hitpoints', 'combat'],
  summoningSynergy_6_15: ['ti_combat_up', 'summoning'],
  summoningSynergy_7_8: ['ti_combat_up', 'summoning'],
  increasedRangedMaxHitBasedOnMaxHitSlayerTask: ['ti_ranged_up', 'slayer'],
  summoningSynergy_7_13: ['ti_dr_up', 'summoning'],
  increasedFlatHPRegenBasedOnRangedMaxHit: ['hitpoints', 'ranged'],
  increasedChanceToApplyBurnWithRanged: ['ranged', 'burn'],
  increasedSlayerCoinsPerMagicDamageSlayerTask: ['slayer_coins', 'magic'],
  summoningSynergy_8_13: ['ti_dr_up', 'summoning'],
  increasedFlatHPRegenBasedOnMagicMaxHit: ['hitpoints', 'magic'],
  increasedRunecraftingEssencePreservation: ['runecrafting', 'preservation'],
  thievingChefNoDamage: ['thieving'],
  decreasedFlatCraftingDragonhideCost: ['crafting'],
  summoningSynergy_9_17: ['interval', 'summoning'],
  increasedGenerousCookPotionCharges: ['potion', 'cooking'],
  summoningSynergy_9_19: ['summoning'],
  increasedRuneEssenceThievingMiner: ['thieving', 'runecrafting'],
  increasedChanceToDoubleLeatherDragonhideCrafting: ['crafting'],
  summoningSynergy_10_17: ['preservation', 'summoning'],
  giveRandomComboRunesRunecrafting: ['runecrafting'],
  increasedFireRunesWhenMakingElementalRunes: ['runecrafting'],
  increasedThievingAutoSellPrice: ['thieving', 'gp'],
  increasedRandomBarChanceThievingMiner: ['thieving'],
  increasedHerbSackChanceThievingFarmer: ['thieving'],
  summoningSynergy_Leprechaun_Devil: ['thieving'],
  increasedDamageReductionAgainstSlayerTasks: ['ti_dr_up', 'slayer'],
  increasedHitpointRegenerationAgainstSlayerTasks: ['hitpoints', 'slayer'],
  decreasedDragonBreathDamage: ['ti_combat_up', 'defence'],
  summoningSynergy_13_14: ['hitpoints', 'combat'],
  increasedCraftingJewelryPreservation: ['crafting', 'preservation'],
  increasedCraftingPotionCharges: ['crafting', 'potion'],
  increasedFiremakingLogGP: ['firemaking', 'gp'],
  doubleSilverGoldSmithingWithSeeingGold: ['smithing', 'potion'],
  decreasedFlatSmithingCoalCost: ['coal', 'smithing'],
  summoningSynergy_Bear_Devil: ['firemaking', 'potion'],
  increasedFlatReflectDamage: ['ti_combat_up'],
  decreasedFlatReflectDamage: ['ti_combat_dn'],
  increasedRolledReflectDamage: ['ti_combat_up'],
  decreasedRolledReflectDamage: ['ti_combat_dn'],
  increasedFlatMinHit: ['ti_combat_up'],
  decreasedFlatMinHit: ['ti_combat_dn'],
  increasedConfusion: ['hitpoints', 'combat'],
  increasedDecay: ['hitpoints', 'combat'],
  increasedDamageTaken: ['ti_combat_dn'],
  decreasedDamageTaken: ['ti_combat_up'],
  increasedGlobalEvasion: ['evasion_up', 'combat'],
  decreasedGlobalEvasion: ['evasion_dn', 'combat'],
  increasedChanceAdditionalSkillResource: ['skill'],
  decreasedChanceAdditionalSkillResource: ['skill'],
  increasedMeleeStrengthBonus: ['ti_strength_up', 'combat'],
  increasedRangedStrengthBonus: ['ti_ranged_up', 'combat'],
  increasedMagicDamageBonus: ['ti_magic_up', 'combat'],
  decreasedMeleeStrengthBonus: ['ti_strength_dn', 'combat'],
  decreasedRangedStrengthBonus: ['ti_ranged_dn', 'combat'],
  decreasedMagicDamageBonus: ['ti_magic_dn', 'combat'],
  increasedMaxAirSpellDmg: ['ti_magic_up', 'air_strike'],
  increasedMaxWaterSpellDmg: ['ti_magic_up', 'water_strike'],
  increasedMaxEarthSpellDmg: ['ti_magic_up', 'earth_strike'],
  increasedMaxFireSpellDmg: ['ti_magic_up', 'fire_strike'],
  decreasedMaxAirSpellDmg: ['ti_magic_dn', 'air_strike'],
  decreasedMaxWaterSpellDmg: ['ti_magic_dn', 'water_strike'],
  decreasedMaxEarthSpellDmg: ['ti_magic_dn', 'earth_strike'],
  decreasedMaxFireSpellDmg: ['ti_magic_dn', 'fire_strike'],
  increasedAgilityObstacleCost: ['agility'],
  decreasedAgilityObstacleCost: ['agility'],
  decreasedSecondaryFoodBurnChance: ['cooking'],
  freeCompost: ['farming'],
  increasedCompostPreservationChance: ['farming'],
  increasedOffItemChance: ['loot', 'bank'],
  increasedFiremakingCoalChance: ['firemaking'],
  doubleItemsSkill: ['skill', 'double'],
  increasedMiningGemChance: ['mining', 'gem'],
  doubleOresMining: ['mining', 'double'],
  increasedBonusCoalMining: ['mining', 'coal'],
  decreasedSmithingCoalCost: ['coal', 'smithing'],
  allowSignetDrops: ['loot'],
  bonusCoalOnDungeonCompletion: ['dungeon', 'coal'],
  increasedMasteryPoolProgress: ['mastery'],
  increasedMeleeLifesteal: ['combat', 'hitpoints'],
  increasedRangedLifesteal: ['ti_ranged_up', 'hitpoints'],
  increasedMagicLifesteal: ['ti_magic_up', 'hitpoints'],
  increasedBleedLifesteal: ['bleed', 'hitpoints'],
  increasedBurnLifesteal: ['burn', 'hitpoints'],
  increasedPoisonLifesteal: ['poison', 'hitpoints'],
  decreasedMeleeLifesteal: ['combat', 'hitpoints'],
  decreasedRangedLifesteal: ['ti_ranged_dn', 'hitpoints'],
  decreasedMagicLifesteal: ['ti_magic_dn', 'hitpoints'],
  decreasedBleedLifesteal: ['bleed', 'hitpoints'],
  decreasedBurnLifesteal: ['burn', 'hitpoints'],
  decreasedPoisonLifesteal: ['poison', 'hitpoints'],
  increasedMeleeCritChance: ['offense_up', 'combat'],
  decreasedMeleeCritChance: ['offense_dn', 'combat'],
  increasedRangedCritChance: ['ti_ranged_up', 'combat'],
  decreasedRangedCritChance: ['ti_ranged_dn', 'combat'],
  increasedMagicCritChance: ['ti_magic_up', 'combat'],
  decreasedMagicCritChance: ['ti_magic_dn', 'combat'],
  meleeProtection: ['evasion_up'],
  rangedProtection: ['evasion_up'],
  magicProtection: ['evasion_up'],
  increasedRuneProvision: ['runecrafting'],
  bypassSlayerItems: ['slayer'],
  curseImmunity: ['curse'],
  increasedDamageReductionPercent: ['ti_dr_up', 'combat'],
  decreasedDamageReductionPercent: ['ti_dr_dn', 'combat'],
  itemProtection: ['bank', 'combat'],
  increasedRedemptionThreshold: ['prayer'],
  increasedRedemptionPercent: ['prayer'],
  autoLooting: ['combat'],
  autoBurying: ['combat'],
  freeProtectItem: ['protect_item', 'combat'],
  stunImmunity: ['stun'],
  sleepImmunity: ['sleep'],
  debuffImmunity: ['combat'],
  burnImmunity: ['burn'],
  poisonImmunity: ['poison'],
  bleedImmunity: ['bleed'],
  increasedRebirthChance: ['combat'],
  increasedChanceToApplyBurn: ['combat', 'burn'],
  decreasedChanceToApplyBurn: ['combat', 'burn'],
  increasedSummoningShardCost: ['summoning'],
  decreasedSummoningShardCost: ['summoning'],
  increasedSummoningCreationCharges: ['summoning'],
  decreasedSummoningCreationCharges: ['summoning'],
  increasedSummoningChargePreservation: ['summoning', 'preservation'],
  decreasedSummoningChargePreservation: ['summoning', 'preservation'],
  decreasedPrayerCost: ['prayer', 'combat'],
  increasedPrayerCost: ['prayer', 'combat'],
  increasedGPMultiplierPer1MGP: ['gp'],
  increasedGPMultiplierCap: ['gp'],
  increasedGPMultiplierMin: ['gp'],
  allowAttackAugmentingMagic: ['magic', 'combat'],
  increasedMeleeStunThreshold: ['stun', 'combat'],
  autoEquipFoodUnlocked: ['cooking', 'combat'],
  autoSwapFoodUnlocked: ['cooking', 'combat'],
  increasedChanceSuccessfulCook: ['cooking'],
  decreasedChanceSuccessfulCook: ['cooking'],
  increasedChancePerfectCookGlobal: ['cooking'],
  decreasedChancePerfectCookGlobal: ['cooking'],
  increasedChancePerfectCookFire: ['cooking'],
  decreasedChancePerfectCookFire: ['cooking'],
  increasedChancePerfectCookFurnace: ['cooking'],
  decreasedChancePerfectCookFurnace: ['cooking'],
  increasedChancePerfectCookPot: ['cooking'],
  decreasedChancePerfectCookPot: ['cooking'],
  increasedThievingStealth: ['thieving'],
  decreasedThievingStealth: ['thieving'],
  increasedAltMagicRunePreservation: ['magic', 'preservation'],
  decreasedAltMagicRunePreservation: ['magic', 'preservation'],
  increasedMinThievingGP: ['thieving', 'gp'],
  decreasedMinThievingGP: ['thieving', 'gp'],
  increasedFishingSpecialChance: ['fishing'],
  decreasedFishingSpecialChance: ['fishing'],
  decreasedAllotmentSeedCost: ['farming'],
  increasedAllotmentSeedCost: ['farming'],
  increasedFrostburn: ['frost_burn', 'hitpoints'],
  increasedSummoningMaxHit: ['summoning', 'combat'],
  decreasedSummoningMaxHit: ['summoning', 'combat'],
  masteryToken: ['mastery'],
  increasedChanceForDiamondFiremaking: ['firemaking', 'diamond'],
  decreasedChanceForDiamondFiremaking: ['firemaking', 'diamond'],
  increasedAfflictionChance: ['afflicted', 'combat'],
  otherStyleImmunity: ['ti_dr_up'],
  meleeImmunity: ['combat'],
  rangedImmunity: ['ranged', 'combat'],
  magicImmunity: ['magic', 'combat'],
  slowImmunity: ['slowed', 'combat'],
  increasedEndOfTurnHealing2: ['hitpoints', 'combat'],
  increasedEndOfTurnHealing3: ['hitpoints', 'combat'],
  increasedEndOfTurnHealing5: ['hitpoints', 'combat'],
  increasedChanceToApplyPoison: ['poison', 'combat'],
  increasedChanceToApplyFrostburn: ['frost_burn', 'combat'],
  increasedMeleeStunChance: ['stun', 'combat'],
  increasedElementalEffectChance: ['ti_magic_up', 'combat'],
  frostBurnImmunity: ['frost_burn', 'combat'],
  increasedPoisonReflectChance: ['poison', 'combat'],
  increasedBleedReflectChance: ['bleed', 'combat'],
  increasedMinNatureSpellDamageBasedOnMaxHit: ['ti_magic_up', 'combat'],
  increasedTotalBleedDamage: ['bleed', 'combat'],
  increasedChanceToIncreaseStunDuration: ['stun', 'combat'],
  increasedSurgeSpellAccuracy: ['surge', 'ti_magic_up'],
  increasedSurgeSpellMaxHit: ['surge', 'ti_magic_up'],
  decreasedRegenerationInterval: ['combat'],
  increasedOnHitSlowMagnitude: ['combat'],
  increasedNonMagicPoisonChance: ['combat'],
  globalEvasionHPScaling: ['evasion_up', 'hitpoints'],
  increasedChanceToPreserveFood: ['hitpoints', 'preservation'],
  allowLootContainerStacking: ['combat'],
  infiniteLootContainer: ['combat'],
  increasedBaseStardustDropQty: ['astrology'],
  increasedGPFromFiremaking: ['firemaking', 'gp'],
  decreasedGPFromFiremaking: ['firemaking', 'gp'],
  bigRon: ['combat'],
  increasedWoodcuttingXPAddedAsFiremakingXP: ['woodcutting', 'firemaking'],
  coalGainedOnCookingFailure: ['cooking', 'coal'],
  halvedWoodcuttingDoubleChance: ['woodcutting', 'double'],
  increasedFlatFarmingYield: ['farming', 'loot'],
  decreasedWoodcuttingXPAddedAsFiremakingXP: ['woodcutting', 'firemaking'],
  increasedChanceForOneExtraOre: ['mining'],
  decreasedChanceForOneExtraOre: ['mining'],
  increasedChanceForQualitySuperiorGem: ['mining', 'gem'],
  decreasedChanceForQualitySuperiorGem: ['mining', 'gem'],
  increasedMeteoriteOre: ['mining', 'meteorite'],
  increasedChanceForAshInWoodcutting: ['woodcutting', 'ash'],
  decreasedChanceForAshInWoodcutting: ['woodcutting', 'ash'],
  increasedChanceForAshInFiremaking: ['firemaking', 'ash'],
  decreasedChanceForAshInFiremaking: ['firemaking', 'ash'],
  increasedChanceForStardustInFiremaking: ['firemaking', 'stardust'],
  decreasedChanceForStardustInFiremaking: ['firemaking', 'stardust'],
  increasedChanceForOneExtraFish: ['fishing'],
  decreasedChanceForOneExtraFish: ['fishing'],
  doubleBoneDrops: ['combat'],
  increasedPrayerPointsWhenHit: ['combat'],
  doubleLogProduction: ['woodcutting'],
  decreasedFlatFarmingYield: ['farming', 'loot'],
  increasedFlatMeleeAccuracyBonusPerAttackInterval: ['offense_up'],
  decreasedFlatMeleeAccuracyBonusPerAttackInterval: ['offense_up'],
  increasedFlatMeleeStrengthBonusPerAttackInterval: ['ti_strength_up'],
  decreasedFlatMeleeStrengthBonusPerAttackInterval: ['ti_strength_dn'],
  increasedFlatRangedAccuracyBonusPerAttackInterval: ['ti_ranged_up'],
  decreasedFlatRangedAccuracyBonusPerAttackInterval: ['ti_ranged_dn'],
  increasedFlatRangedStrengthBonusPerAttackInterval: ['ti_ranged_up'],
  decreasedFlatRangedStrengthBonusPerAttackInterval: ['ti_ranged_dn'],
  increasedFlatMagicAccuracyBonusPerAttackInterval: ['ti_magic_up'],
  decreasedFlatMagicAccuracyBonusPerAttackInterval: ['ti_magic_dn'],
  increasedDamageReductionAgainstMelee: ['ti_dr_up'],
  decreasedDamageReductionAgainstMelee: ['ti_dr_dn'],
  increasedDamageReductionAgainstRanged: ['ti_dr_up'],
  decreasedDamageReductionAgainstRanged: ['ti_dr_dn'],
  increasedDamageReductionAgainstMagic: ['ti_dr_up'],
  decreasedDamageReductionAgainstMagic: ['ti_dr_dn'],
  increasedDamageReductionWithMagic2HWeapon: ['ti_dr_up'],
  decreasedDamageReductionWithMagic2HWeapon: ['ti_dr_dn'],
  increasedMaxHitPercentBasedOnEnemyDamageReduction: ['ti_combat_up'],
  decreasedMaxHitPercentBasedOnEnemyDamageReduction: ['ti_combat_dn'],
  increasedMeleeMaxHitBonusAgainstRanged: ['ti_strength_up', 'combat'],
  decreasedMeleeMaxHitBonusAgainstRanged: ['ti_strength_dn', 'combat'],
  increasedRangedMaxHitBonusAgainstMagic: ['ti_ranged_up', 'combat'],
  decreasedRangedMaxHitBonusAgainstMagic: ['ti_ranged_dn', 'combat'],
  increasedMagicMaxHitBonusAgainstMelee: ['ti_magic_up', 'combat'],
  decreasedMagicMaxHitBonusAgainstMelee: ['ti_magic_dn', 'combat'],
  gainSlayerCoinsBasedOnEnemyCombatLevelMelee: ['slayer_coins', 'combat'],
  gainSlayerCoinsBasedOnEnemyCombatLevelRanged: ['slayer_coins', 'combat'],
  gainSlayerCoinsBasedOnEnemyCombatLevelMagic: ['slayer_coins', 'combat'],
  increasedDamageReductionAgainstBosses: ['ti_dr_up', 'dungeon'],
  decreasedDamageReductionAgainstBosses: ['ti_dr_dn', 'dungeon'],
  increasedChanceDoubleSlayerTaskKill: ['slayer', 'combat'],
  decreasedChanceDoubleSlayerTaskKill: ['slayer', 'combat'],
  increasedDamageTakenAddedAsPrayerPoints: ['prayer', 'combat'],
  decreasedDamageTakenAddedAsPrayerPoints: ['prayer', 'combat'],
  globalAccuracyHPScaling: ['ti_combat_up', 'hitpoints'],
  increasedGPFromNegativeObstacles: ['agility', 'gp'],
  decreasedGPFromNegativeObstacles: ['agility', 'gp'],
  increasedXPFromNegativeObstacles: ['agility', 'xp'],
  decreasedXPFromNegativeObstacles: ['agility', 'xp'],
  increasedMasteryXPFromNegativeObstacles: ['agility', 'mastery'],
  decreasedMasteryXPFromNegativeObstacles: ['agility', 'mastery'],
  increasedChanceGoldenStardust: ['golden_stardust', 'astrology'],
  decreasedChanceGoldenStardust: ['golden_stardust', 'astrology'],
  decreasedEnemyDamageReduction: ['ti_dr_dn', 'combat'],
  increasedEnemyDamageReduction: ['ti_dr_up', 'combat'],
  increasedChanceStardust: ['stardust', 'astrology'],
  decreasedChanceStardust: ['stardust', 'astrology'],
  decreasedThievingStunIntervalPercent: ['thieving', 'stun'],
  increasedThievingStunIntervalPercent: ['thieving', 'stun'],
  decreasedGlobalSkillIntervalPercent: ['interval'],
  increasedGlobalSkillIntervalPercent: ['interval'],
  increasedGlobalStunChance: ['stun', 'combat'],
  decreasedGlobalStunChance: ['stun', 'combat'],
  increasedGlobalSleepChance: ['sleep', 'combat'],
  decreasedGlobalSleepChance: ['sleep', 'combat'],
  increased15SlowStunChance2Turns: ['slowed', 'combat'],
  decreased15SlowStunChance2Turns: ['slowed', 'combat'],
  increasedChanceForArrowShaftsWoodcutting: ['woodcutting'],
  decreasedChanceForArrowShaftsWoodcutting: ['woodcutting'],
  decreasedNonShardCostForEquippedTablets: ['summoning'],
  increasedNonShardCostForEquippedTablets: ['summoning'],
  decreasedPassiveCookInterval: ['cooking', 'interval'],
  increasedPassiveCookInterval: ['cooking', 'interval'],
  increasedSkillPreservationCap: ['skill', 'preservation'],
  decreasedSkillPreservationCap: ['skill', 'preservation'],
  increasedSalamanderCreationCharges: ['summoning'],
  decreasedSalamanderCreationCharges: ['summoning'],
  decreasedJavelinResourceCost: ['fletching'],
  increasedJavelinResourceCost: ['fletching'],
  increasedJavelinProduction: ['fletching'],
  decreasedJavelinProduction: ['fletching'],
  increasedChanceExtraJavelins: ['fletching'],
  decreasedChanceExtraJavelins: ['fletching'],
  increasedChanceExtraMeteoriteOre: ['mining'],
  decreasedChanceExtraMeteoriteOre: ['mining'],
  increasedChanceExtraArrows: ['fletching'],
  decreasedChanceExtraArrows: ['fletching'],
  increasedChanceExtraUnstrungBows: ['fletching'],
  decreasedChanceExtraUnstrungBows: ['fletching'],
  increasedChanceItemToGoldFletching: ['fletching'],
  decreasedChanceItemToGoldFletching: ['fletching'],
  increasedLeprechaunCreationCharges: ['summoning'],
  decreasedLeprechaunCreationCharges: ['summoning'],
  increasedGPFromAgilityPerActiveObstacle: ['agility', 'gp'],
  decreasedGPFromAgilityPerActiveObstacle: ['agility', 'gp'],
  increasedChanceExtraCrossbows: ['fletching'],
  decreasedChanceExtraCrossbows: ['fletching'],
  disableGoldenStardustDrops: ['golden_stardust', 'astrology'],
  increasedBoltProduction: ['fletching'],
  decreasedBoltProduction: ['fletching'],
  decreasedFletchingIntervalWithArrows: ['fletching', 'interval'],
  increasedFletchingIntervalWithArrows: ['fletching', 'interval'],
  increasedGPPerDamage: ['gp', 'combat'],
  decreasedGPPerDamage: ['gp', 'combat'],
  increasedGPBasedOnEnemyCombatLevel: ['gp', 'combat'],
  increasedGPBasedOnSummonDamage: ['gp', 'summoning'],
  decreasedGPBasedOnSummonDamage: ['gp', 'summoning'],
  increasedSlayerCoinsPerDamage: ['slayer_coins', 'combat'],
  decreasedSlayerCoinsPerDamage: ['slayer_coins', 'combat'],
  increasedChanceToIncreaseSleepDuration: ['sleep', 'combat'],
  decreasedChanceToIncreaseSleepDuration: ['sleep', 'combat'],
  increasedCyclopsCreationCharges: ['summoning'],
  decreasedCyclopsCreationCharges: ['summoning'],
  increasedChanceToAvoidStun: ['stun', 'combat'],
  decreasedChanceToAvoidStun: ['stun', 'combat'],
  increasedChanceToAvoidSleep: ['sleep', 'combat'],
  decreasedChanceToAvoidSleep: ['sleep', 'combat'],
  increasedHealWhenStunned: ['hitpoints', 'combat'],
  decreasedHealWhenStunned: ['hitpoints', 'combat'],
  increasedHealWhenSleep: ['hitpoints', 'combat'],
  decreasedHealWhenSleep: ['hitpoints', 'combat'],
  increasedChanceToApplyDeadlyPoisonWhenPoisoned: ['deadly_poison', 'combat'],
  decreasedChanceToApplyDeadlyPoisonWhenPoisoned: ['deadly_poison', 'combat'],
  increasedDamageTakenPerAttack: ['ti_combat_dn'],
  decreasedDamageTakenPerAttack: ['ti_combat_up'],
  increasedDamageTakenWhenAsleep: ['sleep', 'combat'],
  decreasedDamageTakenWhenAsleep: ['sleep', 'combat'],
  increasedDamageTakenWhenStunned: ['stun', 'combat'],
  decreasedDamageTakenWhenStunned: ['stun', 'combat'],
  decreasedPlayerDamageReduction: ['ti_dr_dn', 'combat'],
  increasedDamageDealtIfPoisoned: ['ti_combat_up', 'poison'],
  decreasedDamageDealtIfPoisoned: ['ti_combat_dn', 'poison'],
  increasedMeleeMaxHitFlat: ['ti_strength_up', 'combat'],
  decreasedMeleeMaxHitFlat: ['ti_strength_dn', 'combat'],
  increasedRangedMaxHitFlat: ['ti_ranged_up', 'combat'],
  decreasedRangedMaxHitFlat: ['ti_ranged_dn', 'combat'],
  increasedMagicMaxHitFlat: ['ti_magic_up', 'combat'],
  decreasedMagicMaxHitFlat: ['ti_magic_dn', 'combat'],
  increasedGPFromItemAlchemy: ['magic', 'item_alchemy'],
  increasedChanceToApplyShock: ['shock', 'combat'],
  increasedAbsorbingSkin: ['ti_dr_up', 'combat'],
  increasedDuality: ['ti_attack_interval'],
  increasedChanceToApplyDecayCurse: ['decay', 'magic'],
  increasedRage: ['ti_combat_up'],
  increasedCurseLifesteal: ['hitpoints', 'curse'],
  applyRandomCurseOnSpawn: ['curse', 'combat'],
  increasedChanceDarkBlade: ['dark_blade', 'combat'],
  increasedChanceForCharcoalInFiremaking: ['firemaking'],
  decreasedChanceForCharcoalInFiremaking: ['firemaking'],
  increasedThievingAreaUniqueChance: ['thieving'],
  decreasedThievingAreaUniqueChance: ['thieving'],
  increasedChanceToFindMeteorite: ['astrology', 'meteorite'],
  increasedChanceToFindMushroomWoodcutting: ['woodcutting', 'mushroom'],
  increasedChanceToAvoidThievingStuns: ['thieving', 'stun'],
  increasedChanceAdditionalPerfectItem: ['cooking'],
  increasedMaxHitPercentBasedOnDamageReduction: ['ti_combat_up', 'defence'],
  decreasedMaxHitPercentBasedOnDamageReduction: ['ti_combat_dn', 'defence'],
  halveDamageReduction: ['ti_dr_dn', 'combat'],
  increasedLifestealBasedOnHPRegenEffectiveness: ['hitpoints', 'combat'],
  disableHPRegeneration: ['hitpoints', 'combat'],
  increasedMinMeteorShowerSpellDamage: ['ti_magic_up', 'combat'],
  increasedEndOfTurnEvasion2: ['evasion_up'],
  decreaseEnemyEvasionOnStun: ['ti_combat_up', 'stun'],
  decreaseEnemyEvasionOnSleep: ['ti_combat_up', 'sleep'],
  decreasedEvasionBasedOnDR: ['ti_combat_up'],
  healOnHitBasedOnTargetDR: ['ti_combat_up', 'hitpoints'],
  doubleLifesteal: ['hitpoints', 'combat'],
  increasedMaxHPBurnDamage: ['burn', 'hitpoints'],
  increasedChanceToApplyDeadlyPoison: ['deadly_poison', 'combat'],
  disableLifesteal: ['hitpoints', 'combat'],
  increasedSlayerCoinsBasedOnTargetDR: ['slayer_coins', 'defence'],
  increasedSlayerCoinsPerPoisonDamage: ['slayer_coins', 'poison'],
  increasedChanceStardustCuttingMagicLogs: ['woodcutting', 'stardust'],
  increasedTownshipPopulationCap: ['ts_population', 'township'],
  decreasedTownshipPopulationCap: ['ts_population', 'township'],
  increasedTownshipHappiness: ['ts_happiness', 'township'],
  decreasedTownshipHappiness: ['ts_happiness', 'township'],
  increasedTownshipEducation: ['ts_education', 'township'],
  decreasedTownshipEducation: ['ts_education', 'township'],
  increasedTownshipHealth: ['ts_health', 'township'],
  decreasedTownshipHealth: ['ts_health', 'township'],
  increasedTownshipGPProduction: ['gp', 'township'],
  decreasedTownshipGPProduction: ['gp', 'township'],
  increasedTownshipMaxStorage: ['ts_storage', 'township'],
  decreasedTownshipMaxStorage: ['ts_storage', 'township'],
  increasedTownshipFoodProduction: ['ts_food', 'township'],
  decreasedTownshipFoodProduction: ['ts_food', 'township'],
  increasedTownshipWoodProduction: ['ts_wood', 'township'],
  decreasedTownshipWoodProduction: ['ts_wood', 'township'],
  increasedTownshipOreProduction: ['ts_ore', 'township'],
  decreasedTownshipOreProduction: ['ts_ore', 'township'],
  increasedTownshipStoneProduction: ['ts_stone', 'township'],
  decreasedTownshipStoneProduction: ['ts_stone', 'township'],
  increasedTownshipCoalProduction: ['ts_coal', 'township'],
  decreasedTownshipCoalProduction: ['ts_coal', 'township'],
  increasedTownshipBarProduction: ['ts_bar', 'township'],
  decreasedTownshipBarProduction: ['ts_bar', 'township'],
  increasedTownshipHerbProduction: ['ts_herb', 'township'],
  decreasedTownshipHerbProduction: ['ts_herb', 'township'],
  increasedTownshipRuneEssenceProduction: ['ts_rune', 'township'],
  decreasedTownshipRuneEssenceProduction: ['ts_rune', 'township'],
  increasedTownshipLeatherProduction: ['ts_leather', 'township'],
  decreasedTownshipLeatherProduction: ['ts_leather', 'township'],
  increasedTownshipPotionProduction: ['ts_potion', 'township'],
  decreasedTownshipPotionProduction: ['ts_potion', 'township'],
  increasedTownshipPlankProduction: ['ts_planks', 'township'],
  decreasedTownshipPlankProduction: ['ts_planks', 'township'],
  increasedTownshipClothingProduction: ['ts_clothing', 'township'],
  decreasedTownshipClothingProduction: ['ts_clothing', 'township'],
  increasedTownshipBuildingCost: ['building', 'township'],
  decreasedTownshipBuildingCost: ['building', 'township'],
  increasedTownshipGrasslandsProduction: ['ts_biome_grasslands', 'township'],
  decreasedTownshipGrasslandsProduction: ['ts_biome_grasslands', 'township'],
  increasedTownshipForestProduction: ['ts_biome_forest', 'township'],
  decreasedTownshipForestProduction: ['ts_biome_forest', 'township'],
  increasedTownshipDesertProduction: ['ts_biome_desert', 'township'],
  decreasedTownshipDesertProduction: ['ts_biome_desert', 'township'],
  increasedTownshipWaterProduction: ['ts_biome_water', 'township'],
  decreasedTownshipWaterProduction: ['ts_biome_water', 'township'],
  increasedTownshipSwampProduction: ['ts_biome_swamp', 'township'],
  decreasedTownshipSwampProduction: ['ts_biome_swamp', 'township'],
  increasedTownshipAridPlainsProduction: ['ts_biome_arid_plains', 'township'],
  decreasedTownshipAridPlainsProduction: ['ts_biome_arid_plains', 'township'],
  increasedTownshipMountainsProduction: ['ts_biome_mountains', 'township'],
  decreasedTownshipMountainsProduction: ['ts_biome_mountains', 'township'],
  increasedTownshipValleyProduction: ['ts_biome_valley', 'township'],
  decreasedTownshipValleyProduction: ['ts_biome_valley', 'township'],
  increasedTownshipJungleProduction: ['ts_biome_jungle', 'township'],
  decreasedTownshipJungleProduction: ['ts_biome_jungle', 'township'],
  increasedTownshipSnowlandsProduction: ['ts_biome_snowlands', 'township'],
  decreasedTownshipSnowlandsProduction: ['ts_biome_snowlands', 'township'],
  increasedTownshipFishingDockProduction: ['township'],
  decreasedTownshipFishingDockProduction: ['township'],
  increasedTownshipMagicEmporiumProduction: ['township'],
  decreasedTownshipMagicEmporiumProduction: ['township'],
  increasedTownshipOrchardProduction: ['township'],
  decreasedTownshipOrchardProduction: ['township'],
  increasedTownshipFarmProduction: ['township'],
  decreasedTownshipFarmProduction: ['township'],
  increasedTownshipWoodcuttingProduction: ['township'],
  decreasedTownshipWoodcuttingProduction: ['township'],
  increasedTownshipBlacksmithProduction: ['township'],
  decreasedTownshipBlacksmithProduction: ['township'],
  increasedTownshipTaxPerCitizen: ['gp', 'township'],
  decreasedTownshipTaxPerCitizen: ['gp', 'township'],
  townshipDisableHunting: ['township'],
  increasedTownshipResourceProduction: ['township'],
  decreasedTownshipResourceProduction: ['township'],
  increasedTownshipCoalUsage: ['ts_coal', 'township'],
  decreasedTownshipCoalUsage: ['ts_coal', 'township'],
  increasedTownshipBuildingHappinessPenalties: ['township'],
  decreasedTownshipBuildingHappinessPenalties: ['township'],
  increasedAdditionalAshInFiremaking: ['firemaking', 'ash'],
  decreasedAdditionalAshInFiremaking: ['firemaking', 'ash'],
  increasedSkillMasteryXPPerDeedree: ['skill', 'mastery'],
  increasedSkillMasteryXPPerAmeria: ['skill', 'mastery'],
  increasedSkillMasteryXPPerVale: ['skill', 'mastery'],
  increasedSkillMasteryXPPerQimican: ['skill', 'mastery'],
  increasedSkillMasteryXPPerKo: ['skill', 'mastery'],
  increasedSkillMasteryXPPerArachi: ['skill', 'mastery'],
  increasedSkillMasteryXPPerIridan: ['skill', 'mastery'],
  increasedSkillMasteryXPPerHyden: ['skill', 'mastery'],
  increasedSkillMasteryXPPerSyllia: ['skill', 'mastery'],
  increasedTownshipFoodUsage: ['ts_food', 'township'],
  decreasedTownshipFoodUsage: ['ts_food', 'township'],
  increasedChanceToAvoidCurses: ['curse', 'combat'],
  applyMadnessCurseOnSpawn: ['madness', 'curse'],
  applyTormentCurseOnSpawn: ['torment', 'curse'],
  applyDespairCurseOnSpawn: ['despair', 'curse'],
  freezeImmunity: ['frozen', 'combat'],
  increasedMinPoisonArchaicDmg: ['archaic', 'ti_magic_up'],
  increasedMinInfernalArchaicDmg: ['archaic', 'ti_magic_up'],
  increasedMinLightningArchaicDmg: ['archaic', 'ti_magic_up'],
  increasedChanceToFindLostChest: ['fishing'],
  reducedTargetDamageRedcutionIfBleeding: ['ti_combat_up', 'bleed'],
  increasedAssassin: ['offense_up', 'combat'],
  summoningSynergy_Devil_Eagle: ['thieving'],
  increasedChanceToPreserveConsumable: ['preservation', 'consumable'],
  increasedTownshipDeadStorage: ['township', 'ts_storage'],
  decreasedTownshipDeadStorage: ['township', 'ts_storage'],
  growingMadnessPassive: ['ti_strength_up', 'ti_attack_interval'],
  momentInTimePassive: ['ti_combat_up'],
  reignOverTimePassive: ['ti_combat_up'],
  increasedChanceToApplySleepToTargetWhenHit: ['sleep', 'combat'],
  increasedPlayerRage: ['ti_combat_up'],
  increasedLeviathan: ['ti_combat_up'],
  shadowCloak: ['evasion_up', 'combat'],
  increasedDeadlyToxinsFromHerblore: ['herblore'],
  increasedPoisonSpellAccuracy: ['ti_magic_up', 'combat'],
  increasedInfernalSpellAccuracy: ['ti_magic_up', 'combat'],
  increasedLightningSpellAccuracy: ['ti_magic_up', 'combat'],
  increasedSummoningCreationChargesForEquippedTablets: ['summoning', 'combat'],
  decreasedSummoningIntervalPercentForEquippedTablets: ['summoning', 'combat'],
  increasedMinBirdNestQuantity: ['woodcutting', 'bird_nest'],
  increasedGemVeinChance: ['mining'],
  decreasedGemVeinChance: ['mining'],
  increasedChanceAdditionalBarSmithing: ['smithing'],
  increasedFletchingBoltQuantity: ['fletching'],
  increasedAgilityPillarCost: ['agility'],
  decreasedAgilityPillarCost: ['agility'],
  increasedNonCombatSkillXP: ['skill', 'skill'],
  decreasedNonCombatSkillXP: ['skill', 'skill'],
  increasedFlatMeleeDefenceBonus: ['ti_dr_up', 'combat'],
  increasedFlatRangedDefenceBonus: ['ti_ranged_up', 'combat'],
  increasedFlatStabAttackBonus: ['offense_up', 'combat'],
  increasedFlatSlashAttackBonus: ['ti_strength_up', 'combat'],
  increasedFlatBlockAttackBonus: ['ti_dr_up', 'combat'],
  increasedFlatRangedAttackBonus: ['ti_ranged_up', 'combat'],
  increasedFlatMagicAttackBonus: ['ti_magic_up', 'combat'],
  increasedFlatMeleeStrengthBonus: ['ti_strength_up', 'combat'],
  increasedFlatRangedStrengthBonus: ['ti_ranged_up', 'combat'],
  disableSalamanderItemReduction: ['summoning'],
  decreasedSummoningIntervalForOctopus: ['summoning'],
  decreasedBurnDOTDamage: ['burn', 'combat'],
  increasedBurnDOTDamage: ['burn', 'combat'],
  decreasedBleedDOTDamage: ['bleed', 'combat'],
  increasedBleedDOTDamage: ['bleed', 'combat'],
  decreasedPoisonDOTDamage: ['poison', 'combat'],
  increasedPoisonDOTDamage: ['poison', 'combat'],
  decreasedDeadlyPoisonDOTDamage: ['poison', 'combat'],
  increasedDeadlyPoisonDOTDamage: ['poison', 'combat'],
  increasedMasteryPoolCap: ['mastery'],
  bypassAllSlayerItems: ['slayer', 'combat'],
  increased5DROnBeingHit: ['ti_dr_up', 'combat'],
  increased30Slow5TurnsChance: ['slowed', 'combat'],
  increasedEndOfTurnMaxHealing2: ['combat', 'hitpoints'],
  increasedEvasionAgainstMelee: ['evasion_up', 'combat'],
  increasedEvasionAgainstRanged: ['evasion_up', 'combat'],
  increasedEvasionAgainstMagic: ['evasion_up', 'combat'],
  allowNonMagicCurses: ['curse', 'combat'],
  increasedDamageReductionPer30Defence: ['ti_dr_up', 'combat'],
  increasedElusive: ['combat'],
  increasedMeleeAccuracyMaxHitPer8Strength: ['offense_up', 'strength'],
  increasedDamageReductionWithActivePrayer: ['ti_dr_up', 'prayer'],
  increasedMagicMaxHitWithActivePrayer: ['ti_magic_up', 'prayer'],
  increasedBurnReflectChance: ['burn', 'combat'],
  increasedFrostburnReflectChance: ['frost_burn', 'combat'],
  decreasedMaxHitIfCursed: ['offense_dn', 'combat'],
  decreasedAccuracyIfCursed: ['offense_dn', 'combat'],
  decreasedEvasionIfCursed: ['evasion_dn', 'combat'],
  increasedRangedStrengthBonusPer8Ranged: ['ti_ranged_up', 'combat'],
  increasedTownshipTraderStock: ['ts_trader', 'township'],
  increasedSightRange: ['cartography'],
  decreasedSightRange: ['cartography'],
  increasedSurveyRange: ['cartography'],
  decreasedSurveyRange: ['cartography'],
  increasedHexTravelCost: ['cartography'],
  decreasedHexTravelCost: ['cartography'],
  increasedSurveyInterval: ['cartography', 'interval'],
  decreasedSurveyInterval: ['cartography', 'interval'],
  increasedPaperMakingInterval: ['cartography', 'interval'],
  decreasedPaperMakingInterval: ['cartography', 'interval'],
  increasedMapUpgradeInterval: ['cartography', 'interval'],
  decreasedMapUpgradeInterval: ['cartography', 'interval'],
  increasedSurveyXP: ['cartography'],
  decreasedSurveyXP: ['cartography'],
  increasedMapUpgradeActions: ['cartography', 'map'],
  decreasedMapUpgradeActions: ['cartography', 'map'],
  decreasedInitialMapArtefactValues: ['cartography', 'map'],
  increasedInitialMapArtefactValues: ['cartography', 'map'],
  increasedDigSiteMapSlots: ['map', 'cartography'],
  increasedSieveToolLevel: ['arch_sieve', 'archaeology'],
  increasedTrowelToolLevel: ['arch_trowel', 'archaeology'],
  increasedBrushToolLevel: ['arch_brush', 'archaeology'],
  increasedShovelToolLevel: ['arch_shovel', 'archaeology'],
  increasedFlatBarrierSummonDamage: ['barrier', 'ti_combat_up'],
  increasedBarrierSummonDamage: ['barrier', 'summoning'],
  increasedChanceBarrierBleed: ['barrier', 'bleed'],
  increasedChanceBarrierBurn: ['barrier', 'burn'],
  increasedFlatBarrierSummonDamageMelee: ['barrier', 'summoning'],
  increasedFlatBarrierSummonDamageRanged: ['barrier', 'summoning'],
  increasedFlatBarrierSummonDamageMagic: ['barrier', 'summoning'],
  increasedBarrierSummonDamageIfSlayerTask: ['barrier', 'slayer'],
  enableBarrierBurn: ['barrier', 'burn'],
  increasedGPFromBarrierDamage: ['gp', 'barrier'],
  increasedChanceCrystallization: ['crystallize', 'combat'],
  increasedChanceCrystalSanction: ['aurora', 'combat'],
  disableAttackDamage: ['combat'],
  increasedHiddenSkillLevelPer2Levels: ['skill', 'combat'],
  increasedChanceWeakeningTouch: ['combat'],
  underwaterEffect: ['combat'],
  nulled: ['combat'],
  cleansed: ['combat'],
  increasedChanceToNull: ['combat'],
  increasedChanceToCleanse: ['combat'],
  increasedChanceToDodgeCrystallization: ['crystallize', 'combat'],
  increasedChanceToDodgeCrystalSanction: ['aurora', 'combat'],
  crystallized: ['crystallize', 'combat'],
  increasedChanceToApply5Slow: ['slowed', 'combat'],
  increasedHealEvery200Int: ['hitpoints', 'combat'],
  gain2MaxHitpointsPerTurn: ['hitpoints', 'combat'],
  increasedMaxHitPercentBasedOnTargetCurrentHitpoints: [
    'ti_combat_up',
    'hitpoints',
  ],
  increasedChanceAdditionalSoup: ['cooking'],
  increasedGPFromLogSales: ['woodcutting', 'gp'],
  increasedGPFromRawFishSales: ['fishing', 'gp'],
  increasedChanceForChestOfGemsInWoodcutting: ['woodcutting', 'loot'],
  increasedChanceToLocateAncientRelic: ['ancient_relics'],
  increasedChanceToApplyBlind: ['combat'],
  increasedChanceToPreservePrayerPointsPerPoint: ['prayer', 'combat'],
  increasedMaxHitBasedOnPrayerCost: ['combat', 'prayer'],
  increasedHolyDustFromBlessedOffering: ['magic', 'holy_dust'],
  increasedPrayerPointsFromBurying: ['prayer'],
  increasedChanceToCatchExtraSameAreaFish: ['fishing'],
  increasedHiddenSkillLevelBasedOnLevels: ['skill', 'combat'],
  increasedChanceForGoldFromCrafting30: ['crafting', 'gp'],
  increasedPrayerPointsPerMonsterKill: ['prayer', 'combat'],
  increasedSelfDamageBasedOnCurrentHitpoints: ['hitpoints', 'combat'],
  increasedMeleeStrengthBonusBasedOnSkillLevel: ['ti_strength_up', 'combat'],
  increasedChanceToReceiveNoCombatDrops: ['loot', 'combat'],
  increasedChanceToLocateSkillPet: ['pet'],
  decreasedMeleeAttackIntervalPercent: ['ti_attack_interval', 'ti_combat_up'],
  increasedChanceToDodge: ['evasion_up', 'combat'],
  decreasedEnemyMaximumHitpoints: ['ti_combat_up'],
  increasedAmmoPreservationBypass: ['ranged', 'preservation'],
  increasedRunePreservationBypass: ['magic', 'preservation'],
  increasedMinSpellDmg: ['ti_magic_up', 'combat'],
  increasedPrayerPointsFromBuryingPercent: ['prayer'],
  noDamageFromThievingNPCs: ['thieving'],
  increasedArrowProduction: ['fletching'],
  increasedBaseCraftingConsumableProduction: ['crafting'],
  increasedXPFromMasteryTokens: ['mastery'],
  increasedChanceForEnchantedUrnInCrafting: ['crafting'],
  increasedCombinationRuneProduction: ['runecrafting'],
  halfAttackInterval: ['ti_attack_interval'],
  halfSkillInterval: ['skill', 'interval'],
  halfSkillXP: ['skill', 'xp'],
  halfMasteryXP: ['mastery'],
  increasedEssenceFromMining: ['mining'],
  increasedMasteryTokens: ['mastery'],
  decreasedTownshipRepairCost: ['ts_repair', 'township'],
  decreasedTownshipTraderCost: ['ts_trader', 'township'],
  enableNightfallSeason: ['ts_season_nightfall', 'township'],
  enableSolarEclipseSeason: ['ts_season_eclipse', 'township'],
  increasedLifestealDamageBasedOnCurrentHitpoints: ['hitpoints', 'combat'],
  increasedDamageBasedOnCurrentHitpoints: ['hitpoints', 'combat'],
  increasedDamageBasedOnMaxHitpoints: ['hitpoints', 'combat'],
  increasedHealingWhenHit: ['hitpoints', 'combat'],
  decreasedDamageReductionIfCursed: ['ti_dr_dn', 'curse'],
  increasedDamageTakenIfCursed: ['ti_combat_dn', 'curse'],
  increasedDamageDealtWith2Effects: ['ti_combat_up'],
  increasedDamageTakenWhenSlowed: ['slowed', 'combat'],
  increasedUnholyMarkOnHit: ['unholy', 'combat'],
  increasedDamageTakenBasedOnHP: ['combat'],
  allowUnholyPrayerUse: ['combat', 'prayer'],
  increasedChanceToPreserveUnholyPrayerPoints: ['ti_combat_up', 'unholy'],
  increasedCurseOnHitWithUnholyMark: ['curse', 'unholy'],
  disableTownshipHealthDegradation: ['ts_health', 'township'],
  increasedMinimumTownshipBuildingEfficiency: ['building', 'township'],
  enableLemonSeason: ['lemon', 'township'],
  increasedChanceToPreserveMapCharges: ['cartography', 'map'],
  decreasedChanceToPreserveMapCharges: ['cartography', 'map'],
  applyAttackMasterRelicEffect: ['ancient_relics', 'combat'],
  applyStrengthMasterRelicEffect: ['ancient_relics', 'combat'],
  applyMagicMasterRelicEffect: ['ancient_relics', 'combat'],
  increasedStandardRuneProduction: ['runecrafting'],
  increasedGlobalPreservationChanceBypass: ['preservation'],
  unlockAllSummoningSynergies: ['summoning'],
  agilityItemCostReductionCanReach100: ['agility'],
  decreasedAgilityObstacleItemCost: ['agility'],
  removeDebuffsFromAgility: ['agility'],
  doubleModifiersInAstrologyForMaxedConstellations: ['astrology'],
  increasedGPFlat: ['gp'],
  increasedChanceForGPFromFishing: ['fishing', 'gp'],
  increasedMapRefinementCost: ['cartography', 'map'],
  decreasedMapRefinementCost: ['cartography', 'map'],
  increasedTravelEventChance: ['cartography'],
  decreasedTravelEventChance: ['cartography'],
  increasedChanceToApplyConfusionCurse: ['confusion', 'curse'],
  increasedFlatBarrierDamage: ['barrier', 'ti_combat_up'],
  increasedTinyArtefactChance: ['arch_sieve', 'archaeology'],
  decreasedTinyArtefactChance: ['arch_sieve', 'archaeology'],
  increasedSmallArtefactChance: ['arch_trowel', 'archaeology'],
  decreasedSmallArtefactChance: ['arch_trowel', 'archaeology'],
  increasedMediumArtefactChance: ['arch_brush', 'archaeology'],
  decreasedMediumArtefactChance: ['arch_brush', 'archaeology'],
  increasedLargeArtefactChance: ['arch_shovel', 'archaeology'],
  decreasedLargeArtefactChance: ['arch_shovel', 'archaeology'],
  decreasedTinyArtefactValue: ['arch_sieve', 'archaeology'],
  decreasedSmallArtefactValue: ['arch_trowel', 'archaeology'],
  decreasedMediumArtefactValue: ['arch_brush', 'archaeology'],
  decreasedLargeArtefactValue: ['arch_shovel', 'archaeology'],
  increasedMinimumItemsFoundInArchaeology: ['archaeology'],
  archaeologyVeryRareMapPreservation: ['archaeology', 'map'],
  increasedArchaeologyCommonItemSkillXP: ['archaeology'],
  increasedDigSiteMapCharges: ['map', 'cartography'],
  increasedDamageDealtPerEffect: ['combat'],
  disabledSpecialAttacks: ['combat'],
  increasedBoltSpellMaxHitFlat: ['ti_magic_up', 'combat'],
  increasedMeleeStrengthBonusPer10EnemyDR: ['ti_strength_up', 'defence'],
  increasedGlobalFreezeChance: ['frozen', 'combat'],
  decreasedGlobalFreezeChance: ['frozen', 'combat'],
  decreasedCookingIntervalForBasicSoup: ['cooking', 'interval'],
  increasedRegenPerDamageTaken: ['hitpoints', 'combat'],
  increasedGPPerArchaeologyLevelNoArtefact: ['archaeology', 'gp'],
  increasedPotionsHerblore: ['herblore', 'potion'],
  increasedLemonsPerAction: ['lemon', 'township'],
  doubleConsumablesArchaeology: ['archaeology'],
  convertBoneDropsIntoCake: ['combat'],
  doubleActiveModifiersCartography: ['archaeology'],
  increasedTownshipRepairCost: ['ts_repair', 'township'],
  increasedHiddenSkillLevelPer3Levels: ['skill', 'combat'],
};
