import { ModifierTagMapEntryAttributes } from '../models/ModifierTagMapEntryAttributes';

/**
 * An object mapping all modifiers to tags that represent relevant icons.
 */
export const modifierTagMap = new Map<string, ModifierTagMapEntryAttributes>([
  ['melvorD:accuracyRating', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:meleeAccuracyRating', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:rangedAccuracyRating', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:magicAccuracyRating', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'combat')],
  ['melvorD:meleeMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'}, 'combat')],
  ['melvorD:rangedMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:magicMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:evasion', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:meleeEvasion', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:rangedEvasion', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:magicEvasion', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:flatMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:maxHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:flatHPRegen', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:flatAttackInterval', new ModifierTagMapEntryAttributes('ti_attack_interval', {positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:attackInterval', new ModifierTagMapEntryAttributes('ti_attack_interval', {positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:maxHitpoints', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:flatMaxHitpoints', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:reflectDamage', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:hitpointRegeneration', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:minHitBasedOnMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:attackRolls', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:dragonBreathDamage', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'defence')],
  ['melvorD:flatReflectDamage', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:rolledReflectDamage', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:flatMinHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:flatMagicMinHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'magic')],
  ['melvorD:currentHPDamageTakenOnAttack', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:maxHPDamageTakenOnAttack', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageTaken', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageDealt', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:lifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:meleeLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'attack')],
  ['melvorD:rangedLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'ranged')],
  ['melvorD:magicLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'magic')],
  ['melvorD:bleedLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'bleed')],
  ['melvorD:burnLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'burn')],
  ['melvorD:poisonLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'poison')],
  ['melvorD:meleeCritChance', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:rangedCritChance', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:magicCritChance', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'combat')],
  ['melvorD:meleeProtection', new ModifierTagMapEntryAttributes('evasion_up')],
  ['melvorD:rangedProtection', new ModifierTagMapEntryAttributes('evasion_up')],
  ['melvorD:magicProtection', new ModifierTagMapEntryAttributes('evasion_up')],
  ['melvorD:effectImmunity', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:effectIgnoreChance', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:rebirthChance', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:summoningMaxHit', new ModifierTagMapEntryAttributes('summoning', 'combat')],
  ['melvorD:otherStyleImmunity', new ModifierTagMapEntryAttributes('ti_dr_up')],
  ['melvorD:meleeImmunity', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:rangedImmunity', new ModifierTagMapEntryAttributes('ranged', 'combat')],
  ['melvorD:magicImmunity', new ModifierTagMapEntryAttributes('magic', 'combat')],
  ['melvorD:flatTotalBleedDamage', new ModifierTagMapEntryAttributes('bleed', 'ti_combat_up')],
  ['melvorD:stunDurationIncreaseChance', new ModifierTagMapEntryAttributes('stun', 'combat')],
  ['melvorD:flatRegenerationInterval', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:onHitSlowMagnitude', new ModifierTagMapEntryAttributes('slowed', 'combat')],
  ['melvorD:globalEvasionHPScaling', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'hitpoints')],
  ['melvorD:flatPrayerPointsWhenHit', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:flatMeleeAccuracyBonusPerAttackInterval', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'})],
  ['melvorD:flatMeleeStrengthBonusPerAttackInterval', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'})],
  ['melvorD:flatRangedAccuracyBonusPerAttackInterval', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'})],
  ['melvorD:flatRangedStrengthBonusPerAttackInterval', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'})],
  ['melvorD:flatMagicAccuracyBonusPerAttackInterval', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'})],
  ['melvorD:meleeMaxHitAgainstRanged', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'}, 'combat')],
  ['melvorD:rangedMaxHitAgainstMagic', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:magicMaxHitAgainstMelee', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'combat')],
  ['melvorD:doubleSlayerTaskKillChance', new ModifierTagMapEntryAttributes('slayer', 'combat')],
  ['melvorD:damageTakenAddedAsPrayerPoints', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:accuracyRatingHPScaling', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'hitpoints')],
  ['melvorD:sleepDurationIncreaseChance', new ModifierTagMapEntryAttributes('sleep', 'combat')],
  ['melvorD:stunAvoidChance', new ModifierTagMapEntryAttributes('stun', 'combat')],
  ['melvorD:healWhenStunned', new ModifierTagMapEntryAttributes('stun', 'hitpoints')],
  ['melvorD:healWhenSlept', new ModifierTagMapEntryAttributes('sleep', 'hitpoints')],
  ['melvorD:damageTakenPerAttack', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:frostburnDamage', new ModifierTagMapEntryAttributes('frost_burn', 'combat')],
  ['melvorD:flatMeleeMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'})],
  ['melvorD:flatRangedMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'})],
  ['melvorD:flatMagicMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'})],
  ['melvorD:curseLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'curse')],
  ['melvorD:lifestealBasedOnHPRegenEffectiveness', new ModifierTagMapEntryAttributes('hitpoints')],
  ['melvorD:disableHPRegeneration', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:flatMinMeteorShowerSpellDamage', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'combat')],
  ['melvorD:endOfTurnEvasion2', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'})],
  ['melvorD:decreaseEnemyEvasionOnStun', new ModifierTagMapEntryAttributes('ti_combat_up', 'stun')],
  ['melvorD:decreaseEnemyEvasionOnSleep', new ModifierTagMapEntryAttributes('ti_combat_up', 'sleep')],
  ['melvorD:doubleLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:maxHPBurnDamage', new ModifierTagMapEntryAttributes('burn', 'hitpoints')],
  ['melvorD:disableLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:burnDOTDamageTaken', new ModifierTagMapEntryAttributes('burn', 'combat')],
  ['melvorD:bleedDOTDamageTaken', new ModifierTagMapEntryAttributes('bleed', 'combat')],
  ['melvorD:poisonDOTDamageTaken', new ModifierTagMapEntryAttributes('poison', 'combat')],
  ['melvorD:deadlyPoisonDOTDamageTaken', new ModifierTagMapEntryAttributes('deadly_poison', 'combat')],
  ['melvorD:evasionAgainstMelee', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:evasionAgainstRanged', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:evasionAgainstMagic', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:meleeAccuracyMaxHitPer8Strength', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'})],
  ['melvorD:magicMaxHitWithActivePrayer', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'})],
  ['melvorD:rangedStrengthBonusPer8Ranged', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'})],
  ['melvorD:flatBarrierSummonDamage', new ModifierTagMapEntryAttributes('barrier', 'summoning')],
  ['melvorD:barrierSummonDamage', new ModifierTagMapEntryAttributes('barrier', 'summoning')],
  ['melvorD:flatBarrierSummonDamageMelee', new ModifierTagMapEntryAttributes('barrier', 'summoning')],
  ['melvorD:flatBarrierSummonDamageRanged', new ModifierTagMapEntryAttributes('barrier', 'summoning')],
  ['melvorD:flatBarrierSummonDamageMagic', new ModifierTagMapEntryAttributes('barrier', 'summoning')],
  ['melvorD:barrierSummonDamageIfSlayerTask', new ModifierTagMapEntryAttributes('barrier', 'slayer')],
  ['melvorD:disableAttackDamage', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:cleansed', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:maxHitBasedOnTargetCurrentHitpoints', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:prayerPointPreservationChancePerPoint', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:maxHitBasedOnPrayerCost', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:flatPrayerPointsPerMonsterKill', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:selfDamageOnHitBasedOnCurrentHitpoints', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:noCombatDropChance', new ModifierTagMapEntryAttributes('loot', 'combat')],
  ['melvorD:meleeAttackInterval', new ModifierTagMapEntryAttributes('ti_attack_interval', 'combat')],
  ['melvorD:rangedAttackInterval', new ModifierTagMapEntryAttributes('ti_attack_interval', 'ranged')],
  ['melvorD:magicAttackInterval', new ModifierTagMapEntryAttributes('ti_attack_interval', 'magic')],
  ['melvorD:dodgeChance', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:convertMissIntoHit', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:bypassAmmoPreservationChance', new ModifierTagMapEntryAttributes('ranged', 'preservation')],
  ['melvorD:bypassRunePreservationChance', new ModifierTagMapEntryAttributes('magic', 'preservation')],
  ['melvorD:halveAttackInterval', new ModifierTagMapEntryAttributes('ti_attack_interval')],
  ['melvorD:lifestealDamageBasedOnCurrentHitpoints', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:damageBasedOnCurrentHitpoints', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:damageBasedOnMaxHitpoints', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:healingWhenHit', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:damageDealtWith2Effects', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:unholyMarkOnHit', new ModifierTagMapEntryAttributes('unholy', 'combat')],
  ['melvorD:damageTakenBasedOnHP', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:curseOnHitWithUnholyMark', new ModifierTagMapEntryAttributes('curse', 'unholy')],
  ['melvorD:flatBarrierDamage', new ModifierTagMapEntryAttributes('barrier', {positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageDealtPerEffect', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:regenPerDamageTaken', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:convertBoneDropsIntoCake', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:summoningAttackInterval', new ModifierTagMapEntryAttributes('summoning', 'ti_attack_interval')],
  ['melvorD:flatSummoningAttackInterval', new ModifierTagMapEntryAttributes('summoning', 'ti_attack_interval')],
  ['melvorD:cantAttack', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:cantEvade', new ModifierTagMapEntryAttributes('evasion_dn', 'combat')],
  ['melvorD:cantRegenBarrier', new ModifierTagMapEntryAttributes('barrier', 'combat')],
  ['melvorD:critChance', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:cantSpecialAttack', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:lacerationLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:damageTakenPerMissedAttack', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'combat')],
  ['melvorD:flatAbyssalSlayerAreaEffectNegation', new ModifierTagMapEntryAttributes('slayer', 'combat')],
  ['melvorD:cantMiss', new ModifierTagMapEntryAttributes('ti_combat_up', 'combat')],
  ['melvorD:rawReflectDamage', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:evasionBasedOnCorruptionLevel', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:ablazeDOTDamageTakenIfCorrupted', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:dotDamageTaken', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:bonusCorruptionChance', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:extraCorruptions', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:corruptionCounterRate', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:critMultiplier', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageBasedOnMaxHitpointsSelf', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:toxinDOTDamageTaken', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:ablazeDOTDamageTaken', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:ablazeLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:toxinLifesteal', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:meleeMinHitBasedOnMaxHit', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:rangedMinHitBasedOnMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:magicMinHitBasedOnMaxHit', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'combat')],
  ['melvorD:lacerationDOTDamageTaken', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:voidburstDOTDamageTaken', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:instantCorruptionChance', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:extraLacerationStackChance', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:combatLootDoublingChance', new ModifierTagMapEntryAttributes('loot', 'combat')],
  ['melvorD:damageDealtToBosses', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageDealtToSlayerTasks', new ModifierTagMapEntryAttributes('slayer', {positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageDealtToMonstersInArea', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:damageDealtToAllMonsters', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:autoEatEfficiency', new ModifierTagMapEntryAttributes('autoeat', 'hitpoints')],
  ['melvorD:autoEatThreshold', new ModifierTagMapEntryAttributes('autoeat', 'hitpoints')],
  ['melvorD:autoEatHPLimit', new ModifierTagMapEntryAttributes('autoeat', 'hitpoints')],
  ['melvorD:foodHealingValue', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:prayerPointPreservationChance', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:flatPrayerPointCost', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:ammoPreservationChance', new ModifierTagMapEntryAttributes('ranged', 'preservation')],
  ['melvorD:runePreservationChance', new ModifierTagMapEntryAttributes('magic', 'preservation')],
  ['melvorD:flatMonsterRespawnInterval', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:bankSpace', new ModifierTagMapEntryAttributes('bank')],
  ['melvorD:potionChargePreservationChance', new ModifierTagMapEntryAttributes('potion', 'preservation')],
  ['melvorD:masteryXP', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillXP', new ModifierTagMapEntryAttributes('xp')],
  ['melvorD:flatMiningNodeHP', new ModifierTagMapEntryAttributes('mining')],
  ['melvorD:dungeonEquipmentSwapping', new ModifierTagMapEntryAttributes('equip_swap', 'dungeon')],
  ['melvorD:strongholdEquipmentSwapping', new ModifierTagMapEntryAttributes('equip_swap', 'stronghold')],
  ['melvorD:equipmentSets', new ModifierTagMapEntryAttributes('equip_set', 'combat')],
  ['melvorD:autoSlayerUnlocked', new ModifierTagMapEntryAttributes('auto_slayer', 'combat')],
  ['melvorD:treeCutLimit', new ModifierTagMapEntryAttributes('woodcutting')],
  ['melvorD:skillPreservationChance', new ModifierTagMapEntryAttributes('skill', 'preservation')],
  ['melvorD:slayerTaskLength', new ModifierTagMapEntryAttributes('slayer', 'combat')],
  ['melvorD:globalItemDoublingChance', new ModifierTagMapEntryAttributes('double')],
  ['melvorD:golbinRaidWaveSkipCost', new ModifierTagMapEntryAttributes('golbin', 'combat')],
  ['melvorD:golbinRaidMaximumAmmo', new ModifierTagMapEntryAttributes('golbin', 'ranged')],
  ['melvorD:golbinRaidMaximumRunes', new ModifierTagMapEntryAttributes('golbin', 'magic')],
  ['melvorD:golbinRaidMinimumFood', new ModifierTagMapEntryAttributes('golbin', 'food')],
  ['melvorD:golbinRaidPrayerLevel', new ModifierTagMapEntryAttributes('golbin', 'prayer')],
  ['melvorD:golbinRaidStartingPrayerPoints', new ModifierTagMapEntryAttributes('golbin', 'prayer')],
  ['melvorD:golbinRaidPrayerPointsPerWave', new ModifierTagMapEntryAttributes('golbin', 'prayer')],
  ['melvorD:golbinRaidStartingRuneCount', new ModifierTagMapEntryAttributes('golbin', 'magic')],
  ['melvorD:golbinRaidPassiveSlotUnlocked', new ModifierTagMapEntryAttributes('golbin', 'combat')],
  ['melvorD:golbinRaidPrayerUnlocked', new ModifierTagMapEntryAttributes('golbin', 'prayer')],
  ['melvorD:golbinRaidStartingWeapon', new ModifierTagMapEntryAttributes('golbin', 'combat')],
  ['melvorD:flatPotionCharges', new ModifierTagMapEntryAttributes('potion')],
  ['melvorD:potionCharges', new ModifierTagMapEntryAttributes('potion')],
  ['melvorD:noMiningNodeDamageChance', new ModifierTagMapEntryAttributes('mining')],
  ['melvorD:elementalRuneChance', new ModifierTagMapEntryAttributes('runecrafting')],
  ['melvorD:elementalRuneQuantity', new ModifierTagMapEntryAttributes('runecrafting')],
  ['melvorD:randomHerblorePotionChance', new ModifierTagMapEntryAttributes('herblore')],
  ['melvorD:freeBonfires', new ModifierTagMapEntryAttributes('firemaking')],
  ['melvorD:altMagicSkillXP', new ModifierTagMapEntryAttributes('magic', 'xp')],
  ['melvorD:seedDropConversionChance', new ModifierTagMapEntryAttributes('combat', 'seed')],
  ['melvorD:flatMagicDefenceBonus', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'defence')],
  ['melvorD:hpRegenWhenEnemyHasMoreEvasion', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:summoningAttackLifesteal', new ModifierTagMapEntryAttributes('summoning', 'combat')],
  ['melvorD:bonusFishingSpecialChance', new ModifierTagMapEntryAttributes('fishing')],
  ['melvorD:summoningSynergy_Ent_Leprechaun', new ModifierTagMapEntryAttributes('thieving', 'bird_nest')],
  ['melvorD:woodcuttingJewelryChance', new ModifierTagMapEntryAttributes('woodcutting')],
  ['melvorD:summoningSynergy_4_5', new ModifierTagMapEntryAttributes('mining', 'fishing')],
  ['melvorD:cookingSuccessCap', new ModifierTagMapEntryAttributes('cooking')],
  ['melvorD:miningBarChance', new ModifierTagMapEntryAttributes('mining', 'smithing')],
  ['melvorD:fishingCookedChance', new ModifierTagMapEntryAttributes('fishing', 'cooking')],
  ['melvorD:summoningSynergy_Octopus_Leprechaun', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:magicMinHitBasedOnMaxHitSlayerTask', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'slayer')],
  ['melvorD:meleeMinHitBasedOnMaxHitSlayerTask', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'slayer')],
  ['melvorD:flatHPRegenBasedOnMeleeMaxHit', new ModifierTagMapEntryAttributes('hitpoints', 'combat')],
  ['melvorD:rangedMinHitBasedOnMaxHitSlayerTask', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'slayer')],
  ['melvorD:flatHPRegenBasedOnRangedMaxHit', new ModifierTagMapEntryAttributes('hitpoints', 'ranged')],
  ['melvorD:slayerCoinsPerMagicDamageSlayerTask', new ModifierTagMapEntryAttributes('slayer_coins', 'magic')],
  ['melvorD:flatHPRegenBasedOnMagicMaxHit', new ModifierTagMapEntryAttributes('hitpoints', 'magic')],
  ['melvorD:flatCraftingDragonhideCost', new ModifierTagMapEntryAttributes('crafting')],
  ['melvorD:giveRandomComboRunesRunecrafting', new ModifierTagMapEntryAttributes('runecrafting')],
  ['melvorD:thievingAutoSellPrice', new ModifierTagMapEntryAttributes('thieving', 'currency')],
  ['melvorD:thievingMinerRandomBarChance', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:thievingFarmerHerbSackChance', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:summoningSynergy_Leprechaun_Devil', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:hitpointRegenerationAgainstSlayerTasks', new ModifierTagMapEntryAttributes('hitpoints', 'slayer')],
  ['melvorD:flatSmithingCoalCost', new ModifierTagMapEntryAttributes('coal', 'smithing')],
  ['melvorD:removeSmithingCoalCosts', new ModifierTagMapEntryAttributes('coal', 'smithing')],
  ['melvorD:meleeStrengthBonus', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'}, 'combat')],
  ['melvorD:rangedStrengthBonus', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:magicDamageBonus', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_up'}, 'combat')],
  ['melvorD:agilityObstacleCost', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:freeCompost', new ModifierTagMapEntryAttributes('farming')],
  ['melvorD:compostPreservationChance', new ModifierTagMapEntryAttributes('farming', 'preservation')],
  ['melvorD:bypassCompostPreservationChance', new ModifierTagMapEntryAttributes('farming', 'preservation')],
  ['melvorD:offItemChance', new ModifierTagMapEntryAttributes('loot', 'bank')],
  ['melvorD:miningGemChance', new ModifierTagMapEntryAttributes('mining', 'gem')],
  ['melvorD:bonusCoalMining', new ModifierTagMapEntryAttributes('mining', 'coal')],
  ['melvorD:smithingCoalCost', new ModifierTagMapEntryAttributes('coal', 'smithing')],
  ['melvorD:allowSignetDrops', new ModifierTagMapEntryAttributes('loot')],
  ['melvorD:bonusCoalOnDungeonCompletion', new ModifierTagMapEntryAttributes('dungeon', 'coal')],
  ['melvorD:masteryPoolProgress', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:doubleRuneProvision', new ModifierTagMapEntryAttributes('runecrafting')],
  ['melvorD:bypassSlayerItems', new ModifierTagMapEntryAttributes('slayer')],
  ['melvorD:itemProtection', new ModifierTagMapEntryAttributes('protect_item', 'combat')],
  ['melvorD:redemptionThreshold', new ModifierTagMapEntryAttributes('prayer')],
  ['melvorD:redemptionHealing', new ModifierTagMapEntryAttributes('prayer', 'hitpoints')],
  ['melvorD:autoLooting', new ModifierTagMapEntryAttributes('combat', 'loot')],
  ['melvorD:autoBurying', new ModifierTagMapEntryAttributes('combat', 'prayer')],
  ['melvorD:freeProtectItem', new ModifierTagMapEntryAttributes('protect_item', 'combat')],
  ['melvorD:flatSummoningShardCost', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:summoningChargePreservationChance', new ModifierTagMapEntryAttributes('summoning', 'preservation')],
  ['melvorD:summoningChargePreservationChanceBypass', new ModifierTagMapEntryAttributes('summoning', 'preservation')],
  ['melvorD:prayerPointCost', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:allowAttackAugmentingMagic', new ModifierTagMapEntryAttributes('magic', 'combat')],
  ['melvorD:autoEquipFoodUnlocked', new ModifierTagMapEntryAttributes('cooking', 'combat')],
  ['melvorD:autoSwapFoodUnlocked', new ModifierTagMapEntryAttributes('cooking', 'combat')],
  ['melvorD:successfulCookChance', new ModifierTagMapEntryAttributes('cooking')],
  ['melvorD:perfectCookChance', new ModifierTagMapEntryAttributes('cooking')],
  ['melvorD:thievingStealth', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:altMagicRunePreservationChance', new ModifierTagMapEntryAttributes('magic', 'preservation')],
  ['melvorD:fishingSpecialChance', new ModifierTagMapEntryAttributes('fishing')],
  ['melvorD:farmingSeedCost', new ModifierTagMapEntryAttributes('farming')],
  ['melvorD:flatFarmingSeedCost', new ModifierTagMapEntryAttributes('farming')],
  ['melvorD:foodPreservationChance', new ModifierTagMapEntryAttributes('food', 'preservation')],
  ['melvorD:allowLootContainerStacking', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:woodcuttingXPAddedAsFiremakingXP', new ModifierTagMapEntryAttributes('woodcutting', 'firemaking')],
  ['melvorD:flatCoalGainedOnCookingFailure', new ModifierTagMapEntryAttributes('cooking', 'coal')],
  ['melvorD:flatAbyssalGemsGainedOnCookingFailure', new ModifierTagMapEntryAttributes('cooking', 'gem')],
  ['melvorD:halveWoodcuttingDoubleChance', new ModifierTagMapEntryAttributes('woodcutting')],
  ['melvorD:qualitySuperiorGemChance', new ModifierTagMapEntryAttributes('mining', 'gem')],
  ['melvorD:doubleBoneDrops', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:summoningSynergy_Devil_Eagle', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:xpFromNegativeObstacles', new ModifierTagMapEntryAttributes('agility', 'xp')],
  ['melvorD:masteryXPFromNegativeObstacles', new ModifierTagMapEntryAttributes('agility', 'mastery')],
  ['melvorD:thievingStunInterval', new ModifierTagMapEntryAttributes('thieving', 'stun')],
  ['melvorD:skillInterval', new ModifierTagMapEntryAttributes('interval')],
  ['melvorD:woodcuttingArrowShaftChance', new ModifierTagMapEntryAttributes('woodcutting')],
  ['melvorD:passiveCookingInterval', new ModifierTagMapEntryAttributes('cooking', 'interval')],
  ['melvorD:disableGoldenStardustDrops', new ModifierTagMapEntryAttributes('astrology', 'golden_stardust')],
  ['melvorD:gpFromItemAlchemy', new ModifierTagMapEntryAttributes('magic', 'item_alchemy')],
  ['melvorD:thievingAreaUniqueChance', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:meteoriteLocationChance', new ModifierTagMapEntryAttributes('mining')],
  ['melvorD:thievingStunAvoidanceChance', new ModifierTagMapEntryAttributes('thieving', 'stun')],
  ['melvorD:additionalPerfectItemChance', new ModifierTagMapEntryAttributes('cooking')],
  ['melvorD:additionalItemBasedOnPrimaryQuantityChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatTownshipPopulation', new ModifierTagMapEntryAttributes('ts_population', 'township')],
  ['melvorD:flatTownshipHappiness', new ModifierTagMapEntryAttributes('ts_happiness', 'township')],
  ['melvorD:flatTownshipEducation', new ModifierTagMapEntryAttributes('ts_education', 'township')],
  ['melvorD:townshipHealth', new ModifierTagMapEntryAttributes('ts_health', 'township')],
  ['melvorD:townshipGPProduction', new ModifierTagMapEntryAttributes('gp', 'township')],
  ['melvorD:townshipMaxStorage', new ModifierTagMapEntryAttributes('ts_storage', 'township')],
  ['melvorD:townshipBuildingCost', new ModifierTagMapEntryAttributes('building', 'township')],
  ['melvorD:townshipBuildingProduction', new ModifierTagMapEntryAttributes('building', 'township')],
  ['melvorD:townshipTaxPerCitizen', new ModifierTagMapEntryAttributes('gp', 'township')],
  ['melvorD:townshipDisableHunting', new ModifierTagMapEntryAttributes('township')],
  ['melvorD:townshipResourceProduction', new ModifierTagMapEntryAttributes('township')],
  ['melvorD:townshipCoalUsage', new ModifierTagMapEntryAttributes('ts_coal', 'township')],
  ['melvorD:townshipBuildingHappinessPenalties', new ModifierTagMapEntryAttributes('ts_happiness', 'township')],
  ['melvorD:townshipFoodUsage', new ModifierTagMapEntryAttributes('ts_food', 'township')],
  ['melvorD:consumablePreservationChance', new ModifierTagMapEntryAttributes('consumable', 'preservation')],
  ['melvorD:gemVeinChance', new ModifierTagMapEntryAttributes('mining')],
  ['melvorD:abyssalGemVeinChanceIncrease', new ModifierTagMapEntryAttributes('mining')],
  ['melvorD:agilityPillarCost', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:abyssalWaveAPGain', new ModifierTagMapEntryAttributes('township')],
  ['melvorD:abyssalWaveASCGain', new ModifierTagMapEntryAttributes('township')],
  ['melvorD:nonCombatSkillXP', new ModifierTagMapEntryAttributes('skill', 'xp')],
  ['melvorD:flatMeleeDefenceBonus', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'combat')],
  ['melvorD:flatRangedDefenceBonus', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'ranged')],
  ['melvorD:flatStabAttackBonus', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:flatSlashAttackBonus', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:flatBlockAttackBonus', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:flatRangedAttackBonus', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:flatMagicAttackBonus', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_dn'}, 'combat')],
  ['melvorD:flatMeleeStrengthBonus', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'}, 'combat')],
  ['melvorD:flatRangedStrengthBonus', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:disableSalamanderItemReduction', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:masteryPoolCap', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:bypassAllSlayerItems', new ModifierTagMapEntryAttributes('slayer', 'combat')],
  ['melvorD:allowNonMagicCurses', new ModifierTagMapEntryAttributes('curse', 'combat')],
  ['melvorD:townshipTraderStock', new ModifierTagMapEntryAttributes('ts_trader', 'township')],
  ['melvorD:cartographySightRange', new ModifierTagMapEntryAttributes('cartography')],
  ['melvorD:cartographySurveyRange', new ModifierTagMapEntryAttributes('cartography')],
  ['melvorD:cartographyTravelCost', new ModifierTagMapEntryAttributes('cartography')],
  ['melvorD:cartographySurveyInterval', new ModifierTagMapEntryAttributes('cartography', 'interval')],
  ['melvorD:cartographyPaperMakingInterval', new ModifierTagMapEntryAttributes('cartography', 'interval')],
  ['melvorD:cartographyMapUpgradeInterval', new ModifierTagMapEntryAttributes('cartography', 'interval')],
  ['melvorD:cartographySurveyXP', new ModifierTagMapEntryAttributes('cartography', 'xp')],
  ['melvorD:mapUpgradeActions', new ModifierTagMapEntryAttributes('cartography', 'map')],
  ['melvorD:initialMapArtefactValues', new ModifierTagMapEntryAttributes('cartography', 'map')],
  ['melvorD:sieveToolLevel', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:trowelToolLevel', new ModifierTagMapEntryAttributes('arch_trowel', 'archaeology')],
  ['melvorD:brushToolLevel', new ModifierTagMapEntryAttributes('arch_brush', 'archaeology')],
  ['melvorD:shovelToolLevel', new ModifierTagMapEntryAttributes('arch_shovel', 'archaeology')],
  ['melvorD:ancientRelicLocationChance', new ModifierTagMapEntryAttributes('ancient_relics')],
  ['melvorD:flatAdditionalHolyDustFromBlessedOffering', new ModifierTagMapEntryAttributes('magic', 'holy_dust')],
  ['melvorD:flatPrayerPointsFromBurying', new ModifierTagMapEntryAttributes('prayer')],
  ['melvorD:additionalSameAreaFishChance', new ModifierTagMapEntryAttributes('fishing')],
  ['melvorD:skillPetLocationChance', new ModifierTagMapEntryAttributes('pet')],
  ['melvorD:prayerPointsFromBurying', new ModifierTagMapEntryAttributes('prayer')],
  ['melvorD:ignoreThievingDamage', new ModifierTagMapEntryAttributes('thieving', 'defence')],
  ['melvorD:xpFromMasteryTokens', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:craftingEnchantedUrnChance', new ModifierTagMapEntryAttributes('crafting')],
  ['melvorD:halveSkillInterval', new ModifierTagMapEntryAttributes('book', 'interval')],
  ['melvorD:halveSkillXP', new ModifierTagMapEntryAttributes('book', 'xp')],
  ['melvorD:halveMasteryXP', new ModifierTagMapEntryAttributes('book', 'mastery')],
  ['melvorD:flatMasteryTokens', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:townshipRepairCost', new ModifierTagMapEntryAttributes('ts_repair', 'township')],
  ['melvorD:townshipTraderCost', new ModifierTagMapEntryAttributes('ts_trader', 'township')],
  ['melvorD:enableNightfallSeason', new ModifierTagMapEntryAttributes('ts_season_nightfall', 'township')],
  ['melvorD:enableSolarEclipseSeason', new ModifierTagMapEntryAttributes('ts_season_eclipse', 'township')],
  ['melvorD:enableEternalDarknessSeason', new ModifierTagMapEntryAttributes('township')],
  ['melvorD:allowUnholyPrayerUse', new ModifierTagMapEntryAttributes('combat', 'prayer')],
  ['melvorD:unholyPrayerPointPreservationChance', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'unholy')],
  ['melvorD:disableTownshipHealthDegradation', new ModifierTagMapEntryAttributes('ts_health', 'township')],
  ['melvorD:minimumTownshipBuildingEfficiency', new ModifierTagMapEntryAttributes('building', 'township')],
  ['melvorD:enableLemonSeason', new ModifierTagMapEntryAttributes('lemon', 'township')],
  ['melvorD:bypassGlobalPreservationChance', new ModifierTagMapEntryAttributes('preservation')],
  ['melvorD:unlockAllSummoningSynergies', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:agilityItemCostReductionCanReach100', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:agilityObstacleItemCost', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:removeDebuffsFromAgility', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:harvestingUniqueProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:doubleModifiersInAstrologyForMaxedConstellations', new ModifierTagMapEntryAttributes('astrology')],
  ['melvorD:mapRefinementCost', new ModifierTagMapEntryAttributes('cartography', 'map')],
  ['melvorD:travelEventChance', new ModifierTagMapEntryAttributes('cartography')],
  ['melvorD:tinyArtefactChance', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:smallArtefactChance', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:mediumArtefactChance', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:largeArtefactChance', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:tinyArtefactValue', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:smallArtefactValue', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:mediumArtefactValue', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:largeArtefactValue', new ModifierTagMapEntryAttributes('arch_sieve', 'archaeology')],
  ['melvorD:archaeologyVeryRareMapPreservation', new ModifierTagMapEntryAttributes('archaeology', 'map')],
  ['melvorD:archaeologyCommonItemSkillXP', new ModifierTagMapEntryAttributes('archaeology')],
  ['melvorD:flatDigSiteMapCharges', new ModifierTagMapEntryAttributes('map', 'cartography')],
  ['melvorD:disabledSpecialAttacks', new ModifierTagMapEntryAttributes('combat')],
  ['melvorD:meleeStrengthBonusPer10EnemyDR', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'}, 'defence')],
  ['melvorD:doubleConsumablesArchaeology', new ModifierTagMapEntryAttributes('archaeology')],
  ['melvorD:doubleActiveModifiersCartography', new ModifierTagMapEntryAttributes('archaeology')],
  ['melvorD:soulPointPreservationChance', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:soulPointPreservationChanceBypass', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:skillCostReduction', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:hPRegenBasedOnMaxHP', new ModifierTagMapEntryAttributes('hitpoints')],
  ['melvorD:abyssalSkillXP', new ModifierTagMapEntryAttributes('xp')],
  ['melvorD:regainAbyssalTreeSeedChance', new ModifierTagMapEntryAttributes('farming')],
  ['melvorD:abyssalGemChance', new ModifierTagMapEntryAttributes('gem')],
  ['melvorD:ignoreThievingDamageChance', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:flatAdditionalPrimaryProductQuantity', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatSoulPointsPerMonsterKill', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:flatSoulPointCost', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:soulPointCost', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:flatHarvestingIntensity', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:doubleHarvestingIntensityChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:townshipMaxSoulStorage', new ModifierTagMapEntryAttributes('township')],
  ['melvorD:starFallChance', new ModifierTagMapEntryAttributes('astrology')],
  ['melvorD:skillPreservationCap', new ModifierTagMapEntryAttributes('preservation', 'book')],
  ['melvorD:flatDrakeNestsFromThievingTreant', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:woodcuttingDrakeNestJewelryChance', new ModifierTagMapEntryAttributes('woodcutting')],
  ['melvorD:woodcuttingAXPAddedAsFiremakingAXP', new ModifierTagMapEntryAttributes('woodcutting', 'firemaking')],
  ['melvorD:additionalAbyssalGemChance', new ModifierTagMapEntryAttributes('mining', 'gem')],
  ['melvorD:randomBarThievingWitheringRuinsChance', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:summoningSynergy_Imp_Devil', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:summoningSynergy_Abyssal_Leprechaun_Devil', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:flatSoulPointsWhenHit', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:maxHitWith2AbyssalPrayers', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'prayer')],
  ['melvorD:minimumHarvestingIntensity', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:disableHarvestingVeinDegen', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:abyssalPrayerCost', new ModifierTagMapEntryAttributes('prayer', 'combat')],
  ['melvorD:flatCombatAXPAgainstCorruptedMonsters', new ModifierTagMapEntryAttributes('xp', 'combat')],
  ['melvorD:farmingCropsCannotDie', new ModifierTagMapEntryAttributes('farming')],
  ['melvorD:cannotFishJunk', new ModifierTagMapEntryAttributes('fishing')],
  ['melvorD:fishingAdditionalSpecialItemChance', new ModifierTagMapEntryAttributes('fishing')],
  ['melvorD:miningNodeRespawnInterval', new ModifierTagMapEntryAttributes('mining', 'interval')],
  ['melvorD:runecraftingBaseXPForRunes', new ModifierTagMapEntryAttributes('runecrafting', 'xp')],
  ['melvorD:runecraftingBaseAXPForRunes', new ModifierTagMapEntryAttributes('runecrafting', 'xp')],
  ['melvorD:flatTier1SummoningShardCost', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:flatTier2SummoningShardCost', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:flatTier3SummoningShardCost', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:thievingAreaUniqueChancePercent', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:meleeStrengthBonusWith2HWeapon', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'})],
  ['melvorD:evasionWith2HWeapon', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'combat')],
  ['melvorD:flatMeleeDefenceBonusPerAbyssalLevel', new ModifierTagMapEntryAttributes('combat', 'defence')],
  ['melvorD:flatRangedDefenceBonusPerAbyssalLevel', new ModifierTagMapEntryAttributes('ranged', 'defence')],
  ['melvorD:flatMagicDefenceBonusPerAbyssalLevel', new ModifierTagMapEntryAttributes('magic', 'defence')],
  ['melvorD:abyssalCombatSkillXP', new ModifierTagMapEntryAttributes('xp', 'combat')],
  ['melvorD:rangedStrengthBonusWith2HWeapon', new ModifierTagMapEntryAttributes({positive: 'ti_ranged_up', negative: 'ti_ranged_dn'}, 'combat')],
  ['melvorD:magicDamageBonusWith2HWeapon', new ModifierTagMapEntryAttributes({positive: 'ti_magic_up', negative: 'ti_magic_up'})],
  ['melvorD:flatSoulPointsFromReleasing', new ModifierTagMapEntryAttributes('prayer')],
  ['melvorD:slayerTaskExtensionCost', new ModifierTagMapEntryAttributes('slayer')],
  ['melvorD:slayerTaskCost', new ModifierTagMapEntryAttributes('slayer')],
  ['melvorD:permanentCorruptionCost', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:slashAttackBonus', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'}, 'combat')],
  ['melvorD:meleeAccuracyRatingWith2H', new ModifierTagMapEntryAttributes({positive: 'offense_up', negative: 'offense_dn'})],
  ['melvorD:useNoSummoningChargesAbyssalOctopus', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:flatHiddenSkillLevel', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatSkillInterval', new ModifierTagMapEntryAttributes('interval')],
  ['melvorD:skillItemDoublingChance', new ModifierTagMapEntryAttributes('double', 'book')],
  ['melvorD:additionalPrimaryProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additional2PrimaryProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additional3PrimaryProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additional5PrimaryProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additional8PrimaryProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:doubleItemsSkill', new ModifierTagMapEntryAttributes('double', 'book')],
  ['melvorD:bypassDoubleItemsSkill', new ModifierTagMapEntryAttributes('double', 'book')],
  ['melvorD:skillMasteryXPPerDeedree', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerAmeria', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerVale', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerQimican', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerKo', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerArachi', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerIridan', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerHyden', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:skillMasteryXPPerSyllia', new ModifierTagMapEntryAttributes('mastery')],
  ['melvorD:flatHiddenSkillLevelPer2Levels', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatHiddenSkillLevelBasedOnLevels', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatMeleeStrengthBonusBasedOnSkillLevel', new ModifierTagMapEntryAttributes({positive: 'ti_strength_up', negative: 'ti_strength_dn'})],
  ['melvorD:flatHiddenSkillLevelPer3Levels', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatResistance', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'combat')],
  ['melvorD:flatResistanceAgainstMelee', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'combat')],
  ['melvorD:flatResistanceAgainstRanged', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'ranged')],
  ['melvorD:flatResistanceAgainstMagic', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'magic')],
  ['melvorD:resistance', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'combat')],
  ['melvorD:halveResistance', new ModifierTagMapEntryAttributes('ti_dr_dn', 'combat')],
  ['melvorD:flatResistanceAgainstBosses', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'combat')],
  ['melvorD:flatResistanceAgainstSlayerTasks', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'slayer')],
  ['melvorD:flatResistanceWithMagic2HWeapon', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'magic')],
  ['melvorD:flatResistancePer30Defence', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'defence')],
  ['melvorD:flatResistanceWithActivePrayer', new ModifierTagMapEntryAttributes({positive: 'ti_dr_up', negative: 'ti_dr_dn'}, 'prayer')],
  ['melvorD:maxHitBasedOnResistance', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'defence')],
  ['melvorD:maxHitBasedOnTargetResistance', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'defence')],
  ['melvorD:evasionBasedOnResistance', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:meleeStrengthBonusPer10EnemyResistance', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'}, 'defence')],
  ['melvorD:flatMeleeDefenceBonusBasedOnResistance', new ModifierTagMapEntryAttributes('defence', 'combat')],
  ['melvorD:flatRangedDefenceBonusBasedOnResistance', new ModifierTagMapEntryAttributes('defence', 'ranged')],
  ['melvorD:flatMagicDefenceBonusBasedOnResistance', new ModifierTagMapEntryAttributes('defence', 'magic')],
  ['melvorD:ignoreResistanceWhenAttackingChance', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'defence')],
  ['melvorD:healingOnHitBasedOnTargetResistance', new ModifierTagMapEntryAttributes('hitpoints', 'defence')],
  ['melvorD:healingOnAttackBasedOnResistance', new ModifierTagMapEntryAttributes('hitpoints', 'defence')],
  ['melvorD:maxHitAgainstDamageType', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:accuracyRatingAgainstDamageType', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'})],
  ['melvorD:doubleItemsChanceAgainstDamageType', new ModifierTagMapEntryAttributes('double', 'combat')],
  ['melvorD:damageDealtToDamageTypeSlayerTasks', new ModifierTagMapEntryAttributes({positive: 'ti_combat_up', negative: 'ti_combat_dn'}, 'slayer')],
  ['melvorD:evasionAgainstDamageType', new ModifierTagMapEntryAttributes({positive: 'evasion_up', negative: 'evasion_dn'})],
  ['melvorD:maxHitpointsAgainstDamageType', new ModifierTagMapEntryAttributes('hitpoints')],
  ['melvorD:currencyGain', new ModifierTagMapEntryAttributes('currency')],
  ['melvorD:currencyGainFromCombat', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:flatCurrencyGainFromMonsterDrops', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:flatThievingCurrencyGain', new ModifierTagMapEntryAttributes('currency', 'thieving')],
  ['melvorD:itemSaleCurrencyGain', new ModifierTagMapEntryAttributes('currency', 'bank')],
  ['melvorD:flatCurrencyGainOnEnemyHit', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:flatCurrencyGainOnHitOnSlayerTask', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:flatCurrencyGainWhenHitBasedOnResistance', new ModifierTagMapEntryAttributes('currency', 'defence')],
  ['melvorD:currencyGainOnMonsterKillBasedOnEvasion', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:currencyGainPerDamageDealt', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:currencyGainPerMeleeDamageDealt', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:currencyGainPerRangedDamageDealt', new ModifierTagMapEntryAttributes('currency', 'ranged')],
  ['melvorD:currencyGainPerMagicDamageDealt', new ModifierTagMapEntryAttributes('currency', 'magic')],
  ['melvorD:currencyGainPerMagicDamageDealtOnSlayerTask', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:currencyGainFromMonsterDrops', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:currencyGainFromSlayerTaskMonsterDrops', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:currencyGainOnRegenBasedOnHPGained', new ModifierTagMapEntryAttributes('currency', 'hitpoints')],
  ['melvorD:currencyGainFromLifesteal', new ModifierTagMapEntryAttributes('currency', 'hitpoints')],
  ['melvorD:minThievingCurrencyGain', new ModifierTagMapEntryAttributes('currency', 'thieving')],
  ['melvorD:currencyGainFromNegativeObstacles', new ModifierTagMapEntryAttributes('currency', 'agility')],
  ['melvorD:currencyGainFromAgilityPerActiveObstacle', new ModifierTagMapEntryAttributes('currency', 'agility')],
  ['melvorD:currencyGainFromLogSales', new ModifierTagMapEntryAttributes('currency', 'bank')],
  ['melvorD:currencyGainFromRawFishSales', new ModifierTagMapEntryAttributes('currency', 'bank')],
  ['melvorD:flatCurrencyGain', new ModifierTagMapEntryAttributes('currency')],
  ['melvorD:currencyGainPerDamageDealtBasedOnCurrencyAmount', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:minCurrencyMultiplierPerDamage', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:maxCurrencyMultiplierPerDamage', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:flatCurrencyGainPerArchaeologyLevelNoArtefact', new ModifierTagMapEntryAttributes('currency', 'archaeology')],
  ['melvorD:agilityObstacleCurrencyCost', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:currencyFromHarvestingChanceBasedOnLevel', new ModifierTagMapEntryAttributes('currency', 'book')],
  ['melvorD:flatCurrencyGainOnMonsterKillBasedOnCombatLevel', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:currencyGainFromSlayerTasks', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:currencyGainFromMonsterDropsBasedOnDebuffs', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:flatCurrencyGainFromMeleeSlayerTasksBasedOnCombatLevel', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:flatCurrencyGainFromRangedSlayerTasksBasedOnCombatLevel', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:flatCurrencyGainFromMagicSlayerTasksBasedOnCombatLevel', new ModifierTagMapEntryAttributes('currency', 'slayer')],
  ['melvorD:currencyGainBasedOnSummonDamage', new ModifierTagMapEntryAttributes('currency', 'summoning')],
  ['melvorD:currencyGainBasedOnBarrierDamage', new ModifierTagMapEntryAttributes('currency', 'barrier')],
  ['melvorD:flatCurrencyGainOnEnemyHitBasedOnCombatLevel', new ModifierTagMapEntryAttributes('currency', 'combat')],
  ['melvorD:currencyGainPerPoisonDamage', new ModifierTagMapEntryAttributes('currency', 'poison')],
  ['melvorD:firemakingLogCurrencyGain', new ModifierTagMapEntryAttributes('currency', 'firemaking')],
  ['melvorD:fletchingItemToCurrencyChance', new ModifierTagMapEntryAttributes('currency', 'fletching')],
  ['melvorD:crafting30CurrencyGainChance', new ModifierTagMapEntryAttributes('currency', 'crafting')],
  ['melvorD:fishingCurrencyGainChance', new ModifierTagMapEntryAttributes('currency', 'fishing')],
  ['melvorD:actionsPerClick', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:doubleActionsPerClickChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:extraActionPerClickChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatSlayerAreaEffectNegation', new ModifierTagMapEntryAttributes('slayer')],
  ['melvorD:doubleSoulDropChance', new ModifierTagMapEntryAttributes('prayer', 'double')],
  ['melvorD:doubleSoulDrops', new ModifierTagMapEntryAttributes('prayer', 'double')],
  ['melvorD:placeholderModifier', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:farmingSeedReturn', new ModifierTagMapEntryAttributes('farming')],
  ['melvorD:fishingMasteryDoublingChance', new ModifierTagMapEntryAttributes('fishing', 'mastery')],
  ['melvorD:halveAgilityObstacleNegatives', new ModifierTagMapEntryAttributes('agility')],
  ['melvorD:nonShardSummoningCostReduction', new ModifierTagMapEntryAttributes('summoning')],
  ['melvorD:runecraftingRuneCostReduction', new ModifierTagMapEntryAttributes('runecrafting')],
  ['melvorD:flatBasePrimaryProductQuantity', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatBasePrimaryProductQuantityChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:basePrimaryProductQuantity', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:randomProductChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatBaseRandomProductQuantity', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:currencyGainBasedOnProduct', new ModifierTagMapEntryAttributes('currency', 'book')],
  ['melvorD:additionalRandomSkillItemChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additionalRandomSkillItemChancePerInterval', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additionalRandomGemChance', new ModifierTagMapEntryAttributes('book', 'gem')],
  ['melvorD:additionalRandomAbyssalGemChance', new ModifierTagMapEntryAttributes('book', 'gem')],
  ['melvorD:additionalRandomFragmentChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additionalRandomFiremakingOilChance', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:additionalRandomAbyssalGemChancePerInterval', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:flatAdditionalSkillItem', new ModifierTagMapEntryAttributes('book')],
  ['melvorD:firemakingBonfireInterval', new ModifierTagMapEntryAttributes('firemaking', 'interval')],
  ['melvorD:astrologyModifierCost', new ModifierTagMapEntryAttributes('astrology')],
  ['melvorD:flatAdditionalThievingCommonDropQuantity', new ModifierTagMapEntryAttributes('thieving')],
  ['melvorD:flatSpellRuneCost', new ModifierTagMapEntryAttributes('magic')],
  ['melvorD:flatAttackSpellRuneCost', new ModifierTagMapEntryAttributes('magic')],
  ['melvorAoD:digSiteMapSlots', new ModifierTagMapEntryAttributes('archaeology')],
  ['melvorAoD:mapChargePreservationChance', new ModifierTagMapEntryAttributes('archaeology')],
  ['melvorAoD:artefactValue', new ModifierTagMapEntryAttributes('archaeology')],
  ['melvorIta:maxHarvestingIntensity', new ModifierTagMapEntryAttributes('book')],
]);